### ISSUE TITLE
Investigate http://162.217.248.187/game/220965

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#105]
Multiple mates in one were missed by black here...

**Comment by jkiliani** [comment]
What does the training data look like for this game? It's quite possible the mate was eventually found but either couldn't make it far enough up the visit count list in time, or temperature simply picked the wrong move each time.

One possible approach to reduce the endgame bungling would be to not use temperature=1 for the whole game anymore.

**Comment by Error323** [comment]
Yes I think this represents a good case for #67

**Comment by killerducky** [comment]
Is there a chess GUI that I can click on a position, tell the engine to analyze, and I can see the debug output? Cutechess I can't figure how to load pgn files. Scid I loaded the pgn, the engine will analyze the move I tell it, but it only shows the PV, the extended debug info is not shown.

**Comment by jjoshua2** [comment]
I have used many different gui and never seen all the output before.
Closest is an adapter that logs all communication both ways. Like polyglot
adapter or I forget the other one that you can use for uci engine over ssh

**Comment by killerducky** [comment]
Here is output for one of the missed mates. The problem is the policy network is very bad, the two checkmate moves have 0.16% and 0.02% chance, and get 0 of the 800 playouts. So it has nothing to do with the temperature in this case.

I also ran with `-n` a few times and in that case it started finding the mate sometimes, but never soon enough to make it the top move. But with training it the network will usually see those mate moves are better than 0.16%. The next generation will investigate it more earlier, and it will rise over time.

```
./lczero -w ~/lcnetworks/latest.txt -p800 --noponder -t1
position fen 8/8/5k2/1P3np1/1rP1p2p/5Pr1/3qB3/K7 b - - 2 46
go
e4f3 ->     474 (V: 98.19%) (N: 46.72%) PV: e4f3 e2f3 b4c4 f3e4 c4e4 a1b1 e4e3 b5b6
g5g4 ->     126 (V: 97.24%) (N: 17.52%) PV: g5g4 f3e4 d2e2 e4f5 f6f5 c4c5 b4b5
e4e3 ->      79 (V: 96.79%) (N: 12.34%) PV: e4e3 e2f1 b4c4 f1c4 e3e2 c4e2
b4b3 ->      71 (V: 96.55%) (N: 11.53%) PV: b4b3 f3e4 d2e2 e4f5 f6f5 c4c5 b3b5
g3g2 ->      28 (V: 96.42%) (N:  4.79%) PV: g3g2 f3e4 d2e2 e4f5 b4c4 a1b1
h4h3 ->      22 (V: 96.61%) (N:  3.66%) PV: h4h3 f3e4 d2e2 c4c5 b4b5
f6e5 ->       0 (V: 84.30%) (N:  0.60%) PV: f6e5 
d2d1 ->       0 (V: 84.30%) (N:  0.43%) PV: d2d1 
f5e7 ->       0 (V: 84.30%) (N:  0.32%) PV: f5e7 
f5g7 ->       0 (V: 84.30%) (N:  0.23%) PV: f5g7 
f5d4 ->       0 (V: 84.30%) (N:  0.22%) PV: f5d4 
f5e3 ->       0 (V: 84.30%) (N:  0.19%) PV: f5e3 
d2c1 ->       0 (V: 84.30%) (N:  0.16%) PV: d2c1  <<<<<<<<<<<<
f5d6 ->       0 (V: 84.30%) (N:  0.14%) PV: f5d6 
d2e2 ->       0 (V: 84.30%) (N:  0.13%) PV: d2e2 
f5h6 ->       0 (V: 84.30%) (N:  0.12%) PV: f5h6 
g3f3 ->       0 (V: 84.30%) (N:  0.08%) PV: g3f3 
b4c4 ->       0 (V: 84.30%) (N:  0.07%) PV: b4c4 
d2e1 ->       0 (V: 84.30%) (N:  0.07%) PV: d2e1 
f6e7 ->       0 (V: 84.30%) (N:  0.07%) PV: f6e7 
f6e6 ->       0 (V: 84.30%) (N:  0.06%) PV: f6e6 
g3h3 ->       0 (V: 84.30%) (N:  0.05%) PV: g3h3 
d2f4 ->       0 (V: 84.30%) (N:  0.04%) PV: d2f4 
g3g1 ->       0 (V: 84.30%) (N:  0.04%) PV: g3g1 
b4b1 ->       0 (V: 84.30%) (N:  0.04%) PV: b4b1 
f6g6 ->       0 (V: 84.30%) (N:  0.04%) PV: f6g6 
d2c2 ->       0 (V: 84.30%) (N:  0.04%) PV: d2c2 
d2a2 ->       0 (V: 84.30%) (N:  0.04%) PV: d2a2 
f6g7 ->       0 (V: 84.30%) (N:  0.04%) PV: f6g7 
d2d5 ->       0 (V: 84.30%) (N:  0.03%) PV: d2d5 
b4a4 ->       0 (V: 84.30%) (N:  0.03%) PV: b4a4 
b4b2 ->       0 (V: 84.30%) (N:  0.02%) PV: b4b2 
d2d6 ->       0 (V: 84.30%) (N:  0.02%) PV: d2d6 
d2c3 ->       0 (V: 84.30%) (N:  0.02%) PV: d2c3 
d2d7 ->       0 (V: 84.30%) (N:  0.02%) PV: d2d7 
d2b2 ->       0 (V: 84.30%) (N:  0.02%) PV: d2b2 <<<<<<<<<<<<<
d2e3 ->       0 (V: 84.30%) (N:  0.01%) PV: d2e3 
d2d3 ->       0 (V: 84.30%) (N:  0.01%) PV: d2d3 
f6f7 ->       0 (V: 84.30%) (N:  0.01%) PV: f6f7 
d2d8 ->       0 (V: 84.30%) (N:  0.01%) PV: d2d8 
b4b5 ->       0 (V: 84.30%) (N:  0.01%) PV: b4b5 
d2d4 ->       0 (V: 84.30%) (N:  0.00%) PV: d2d4 
g3g4 ->       0 (V: 84.30%) (N:  0.00%) PV: g3g4 
```

**Comment by glinscott** [comment]
@jkiliani Uploading all the training data is next on my list after getting match support implemented.

Thanks for looking @killerducky!

If the network never visits the mates though, it's not going to get any training signal from this position at least though.  I guess we have to rely on `--randomize` in positions like this to expose the network to the mate, and hope that's enough signal for it to learn from.

**Comment by jkiliani** [comment]
I'm curious about one thing here: The playout distribution shown by @killerducky has the two mating moves marked, this wasn't added afterwards, correct? If the engine actually finds mate-in-one moves in the search tree, why does this alone not immediately override the whole search?

**Comment by jjoshua2** [comment]
I'm guessing because there no special case for winning. We could maybe add
one like leela go dumbpass flag or checking if it's won to pass

**Comment by killerducky** [comment]
@jkiliani I added the markers. Of course it's possible to add special cases but I think that is a mistake because missing checkmates is the easiest way to find and fix bugs. If you special case this maybe you can 1 Elo point, but now finding further bugs will be more difficult. 

Also I want to encourage more people to run these cases and look at the debug output. Also try adding `-d` and you'll see it does start searching the checkmate some. I know it takes more time but we have enough people speculating, we need more people debugging and writing code.

**Comment by jkiliani** [comment]
@killerducky Just looked at the position on http://www.chess-poster.com/english/fen/fen_epd_viewer.htm. Qc1 is not actually checkmate, only Qb2 is. But I also have trouble getting the net to find that move, even at higher playouts and with Dirichlet noise. By the way, how do you create a FEN code from just watching a replay on the server?

**Comment by killerducky** [comment]
Oops, editied out Qc1!  :)

I did some more testing with noise. It searches the checkmate 6/20 times. Average visits over all 20 trials is 21.1, divide by 800 visits = 2.6%. This means the next generation will set the policy for this move to 2.6%. Next generation will find more often and earlier, raising it more, etc.

```
cat commands.txt | ./lczero -w ~/lcnetworks/latest.txt -p800 --noponder -n -t1 | grep d2b2 >> test.log
(repeat 20 times)
cat test.log
info string d2b2 ->       0 (V: 84.30%) (N:  0.04%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.41%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.01%) PV: d2b2 
info string d2b2 ->      63 (V: 100.00%) (N:  1.00%) PV: d2b2 
info string d2b2 ->      48 (V: 100.00%) (N:  0.87%) PV: d2b2 
info string d2b2 ->      83 (V: 100.00%) (N:  2.26%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.32%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.01%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.02%) PV: d2b2 
info string d2b2 ->      59 (V: 100.00%) (N:  1.20%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.01%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.04%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.39%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.02%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.25%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.59%) PV: d2b2 
info string d2b2 ->      50 (V: 100.00%) (N:  0.74%) PV: d2b2 
info string d2b2 ->     119 (V: 100.00%) (N:  2.83%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.10%) PV: d2b2 
info string d2b2 ->       0 (V: 84.30%) (N:  0.34%) PV: d2b2 
```

Example of one noise hit. Notice the checkmate has 82 visits, while f6e6 with similar N value has only 7. Once the checkmate is searched once the search will focus on it very quickly, no need for special code.
```
info string e4f3 ->     347 (V: 98.06%) (N: 35.05%) PV: e4f3 e2f3 b4c4 f3e2 c4c1
info string g5g4 ->      94 (V: 97.15%) (N: 13.16%) PV: g5g4 f3e4 d2e2 e4f5 f6f5 c4c5
info string d2b2 ->      82 (V: 100.00%) (N:  1.64%) PV: d2b2 
info string e4e3 ->      61 (V: 96.78%) (N:  9.51%) PV: e4e3 e2f1 b4c4 f1c4 e3e2 c4e2
info string b4b3 ->      52 (V: 96.45%) (N:  8.73%) PV: b4b3 f3e4 d2e2 e4f5 f6f5 c4c5 b3b5
info string b4c4 ->      42 (V: 97.77%) (N:  4.82%) PV: b4c4 f3e4 c4e4 e2f1 e4e3 b5b6
info string g3g2 ->      29 (V: 96.44%) (N:  4.94%) PV: g3g2 f3e4 d2e2 e4f5 b4c4 a1b1
info string f5g7 ->      22 (V: 96.87%) (N:  3.37%) PV: f5g7 f3e4 d2e2 b5b6 b4c4
info string h4h3 ->      17 (V: 96.49%) (N:  2.76%) PV: h4h3 f3e4 d2e2 c4c5 b4b5
info string b4b2 ->      11 (V: 97.07%) (N:  1.65%) PV: b4b2 f3e4 d2e2 e4f5 f6f5 c4c5
info string d2d1 ->      11 (V: 91.86%) (N:  4.00%) PV: d2d1 e2d1 e4f3 d1f3 b4c4 f3e2
info string f6e6 ->       7 (V: 97.12%) (N:  1.01%) PV: f6e6 f3e4 d2e2 e4f5 e6f5
```

**Comment by jkiliani** [comment]
Just did a similar trial but you beat me to it ;) I repeated the eval with 800 visits 10 times, got 4 noise hits. The number of visits for Qb2 in those four tries were 132, 143, 56 and 53. This should mean that the training data for future nets will find these mates sooner just as you said.

**Comment by glinscott** [comment]
Ok, thanks everyone for looking!  Will leave this open until the next network, so we can compare the results.

**Comment by Dorus** [comment]
It might take more than 1 network to learn this actual move, but if you look at the stats, you see the nr of draws go down, the nr of no materials go down, mates come earlier etc, so overall the network is moving in the right direction.

What you can expect from early elo progress, and this is visible in the AG/AGZ/AZ papers as well on LeelaZ, early on elo goes up fast, then slows down a bit untill the network starts to understand the game and break out of random territory. After that elo should begin to climb VERY fast, and only slow down once the network reaches capacity (or understands the game 100%, whatever comes first).

**Comment by jkiliani** [comment]
I agree that one network is optimistic here, since the calculation made by @killerducky for the next network generation would apply only if the entire training data for that net was made up from gen5, which won't be the case. Still, we should see a slight improvement at least.

**Comment by killerducky** [comment]
Ok I think not giving the game history threw off my previous results. I've found a better method to test this stuff. Here are results for gen 6, 9, and 11. (I think gen6 is what the original game was? not sure).

Gen006 actually does find the mate after all in my first post N was 0.02%. Now it is 0.95%. I'm guessing the 7 blank history planes confused the net to think it's the opening. I imagine it was surprised when the 8th plane suddenly had a Black queen on the 7th rank!
```
gen006_de1d.log
info string d2b2 ->     550 (V: 100.00%) (N:  0.95%) PV: d2b2
info string g5g4 ->      20 (V: 95.40%) (N:  3.99%) PV: g5g4 f3e4 b4c4 e4f5 c4f4 b5b6
info string e4f3 ->      20 (V: 89.68%) (N:  7.71%) PV: e4f3 e2f3 b4b5 c4b5 h4h3 b5b6 d2c2
```

Gen009 and Gen011 find the checkmate but not a the top move. Top move is pawn takes pawn, not a bad move really. Especially Gen011's first instinct is very strong to capture the pawn or the bishop. Finally note that by Gen011 the new training target output for d2b2 would be 169/800=21.1%. Hopefully Gen011 is producing many such positions where it's finding mate-in-ones and the net will generalize that.
```
gen009_b91f.log
info string e4f3 ->     106 (V: 97.36%) (N: 13.06%) PV: e4f3 e2f3 b4c4 f3e4 c4e4 a1b1
info string d2e2 ->      97 (V: 98.96%) (N:  5.47%) PV: d2e2 f3e4 b4c4 e4f5 c4c1
info string d2b2 ->      85 (V: 100.00%) (N:  1.08%) PV: d2b2

gen011_6d2e.log
info string e4f3 ->     185 (V: 97.39%) (N: 21.10%) PV: e4f3 e2f3 b4c4 a1b1 g3f3 b5b6 h4h3
info string d2b2 ->     169 (V: 100.00%) (N:  0.82%) PV: d2b2
info string d2e2 ->      80 (V: 96.87%) (N:  8.96%) PV: d2e2 f3e4 b4c4 b5b6 c4e4 b6b7 h4h3
```

**Comment by killerducky** [comment]
See procedure here: https://github.com/glinscott/leela-chess/issues/106#issuecomment-373256679

**Comment by glinscott** [comment]
Thanks for re-running this!!  I am convinced :).
