### ISSUE TITLE
Why is Gen5 called "online" ?

### ISSUE THREAD

**Issue by CMCanavessi** [glinscott/leela-chess#110]
If you go to http://162.217.248.187/networks and download network b91f353d and uncompress it, you'll get a file called "online-64x6-30000.txt", shouldn't this be gen5-64x6.txt, like the previous ones, just for consistency? 
If you download the latest network 7f8f398e you do get a file called gen6: "gen6-64x6-28000.txt". What are those numbers, 30000 and 28000? I think there should be a standarized name for the different gens/networks not to confuse noobs like me :)

**Comment by Error323** [comment]
Gen5 was trained in an online manner, meaning directly from the chunks on the server. The other generations were trained by first constructing an offline dataset. This is very timeconsuming and error prone. The number postfix represent the number of steps in the trainingprocess that were required to reach these weights.

**Comment by st90115** [comment]
at this phase , it does some experiments. Can it add some command on the network page of the LCZero website to let others know the progress?
