### ISSUE TITLE
Server web UI is not mobile friendly

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#113]
Main menu is not visible when visiting http://162.217.248.187/ from mobile.

The site doesn't have to be super mobile-friendly and look good, but it would be nice to be able to check current status from phone (number of games played on the latest network and stats charts).

**Comment by davidsoncolin** [comment]
The sidebar is completely hidden on my mobile screen, so navigation to other pages is thwarted.

To fix, replace:
`<nav class="col-md-2 d-none d-md-block bg-light sidebar"`
with
`<nav class="col-2 d-block bg-light sidebar">`
(the first says the sidebar is not visible for small and extra-small screens; the second says it's always visible and takes up about 2/12 of the screen)

replace
`<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">`
with
`<main role="main" class="col-9 ml-auto col-lg-10 pt-3 px-4">`
(the first says the body fills the frame for small and extra-small screens, which assumed the sidebar was hidden)

If the sidebar it supposed to disappear on small screens, perhaps a list with the same content should appear in the navbar?

**Comment by glinscott** [comment]
Thanks!  I did this, and you can at least sort of see the sidebar now :).  Would be happy if anyone with more HTML design skills took a look at this though!
