### ISSUE TITLE
How to run 2 or more clients of lczero without crush?

### ISSUE THREAD

**Issue by kris-computer-go** [glinscott/leela-chess#114]
When I try to run 2 or more clients of lczero they started to crush one by one until only last is working.
It's always like this when two games are finished around the same time and client try to send one of them when another one is just sended.
Another problem I've noticed is if I create the new catalog for lczero and try to start it crush immediately.
Also it crush on other PC if I start with the same user and password.
I would like to run 4 instances on first PC and 4 instances on the second. How to do it?

**Comment by mooskagh** [comment]
Are you on windows or linux?

On linux, I can just start two copies of ./client from the same directory
with the same parameters (same username and password) and it works fine.
Every client creates a separate data-XXXXX/ subdirectory.

**Comment by kris-computer-go** [comment]
Windows 10

**Comment by jkormu** [comment]
I had to run two clients in separate folders for it to be stable. Made a copy of the folder that ran 1 instance successfully and started another client in the copied folder. For Getting the first client run I used the EASYMODE instructions of #88 .

In Linux I am able to run two clients from the same directory just fine.

**Comment by Error323** [comment]
We're using the process id to create a unique directory see https://github.com/glinscott/leela-chess/blob/master/go/src/client/main.go#L68. It's all a bit hacky right now, I think it's not working for Windows, perhaps @glinscott knows why.

**Comment by panNorton** [comment]
I can confirm that running separate instances in separate folders works. 

Is there an easy way to make it work on CPU (I would like to make it run on some Azure VMs)?

**Comment by Error323** [comment]
@panNorton I just pushed a patch that should allow CPU only clients. Please recompile the master branch and deploy :)

**Comment by Uriopass** [comment]
I think we should name the folder using something unique other than the PID since with windows it always returns 1.. Maybe something like the time, or we could loop over dir-%d and check if the directory already exists. I know a bit of go and tried my hand with the I/O with the settings.json implementation, I'll do a PR tomorrow.

**Comment by glinscott** [comment]
I think that was from the v0.1 release.  Can you try with the v0.2 release and let me know?  It should work properly now.
