### ISSUE TITLE
Little ELO Progress

### ISSUE THREAD

**Issue by brianprichardson** [glinscott/leela-chess#12]
This has been a rather small effort so far, but after the initial training for less than 50 games, and then 100 (base), I generated 600 (new) games and optimized again (leelaz-model-154000.txt).  The results are below, with almost no improvement.  Perhaps this is expected, but I was hoping for a little bump.  Maybe the incremental improvement is lost in the noise for the current settings

Score of lc_new vs lc_base: 22 - 20 - 358  [0.502] 400
Elo difference: 1.74 +/- 11.02

**Comment by glinscott** [comment]
@brianprichardson yes, this is what I was noticing as well.  I think the next steps are validating the UCT search by doing some supervised learning.

The thing I noticed in the training games (if you search training.out), is that the vast majority were draws.  It got to about 99% draws, which means the network just learns to predict a draw.  I was going to implement some bucketing to give it 33% draw, 33% win and 33% loss as training data.  But first up is validation of the search/training pipeline.

**Comment by glinscott** [comment]
To get a count of WLD from the training games, I did `cat training.out | grep Score | sort | uniq -c`

**Comment by brianprichardson** [comment]
For nearly all games:
   1304 Score: 0
     60 Score: 1
     49 Score: -1

**Comment by Error323** [comment]
I think an implementation of AlphaZero such that the network keeps getting trained continuously and each selfplay game starts with a weight update will improve it's play. I'll do some experimentation on this. Also I would like to refactor the network such that history is removed.

**Comment by joergoster** [comment]
@glinscott Does the NN already know how to win? Maybe this needs to be trained first? If you don't know how to mate you can't win in chess.
Otherwise it may be possible that the NN is learning this by pure accident, which may take a huge number of games. And I don't mean thousands of games ... ;-)

**Comment by grondilu** [comment]
>  The signal is nearly all draws, so I think the network will have quite a tough time learning to extract wins/losses...

Possibly a dumb question but : why not ignore draws for training?  If a games end up in a draw, don't update the weights and just run an other game.

**Comment by Error323** [comment]
I think we can safely close this now, agreed @brianprichardson ?
