### ISSUE TITLE
Link error Win10 Visual Studio

### ISSUE THREAD

**Issue by Akababa** [glinscott/leela-chess#128]
I'm getting the following error on build with the leela-chess2017.sln:

`LNK2019	unresolved external symbol "public: static class NNCache & __cdecl NNCache::get_NNCache(void)" (?get_NNCache@NNCache@@SAAEAV1@XZ) referenced in function "public: static struct std::pair<class std::vector<struct std::pair<float,enum Move>,class std::allocator<struct std::pair<float,enum Move> > >,float> __cdecl Network::get_scored_moves(struct BoardHistory const &,struct Network::DebugRawData *,bool)" (?get_scored_moves@Network@@SA?AU?$pair@V?$vector@U?$pair@MW4Move@@@std@@V?$allocator@U?$pair@MW4Move@@@std@@@2@@std@@M@std@@AEBUBoardHistory@@PEAUDebugRawData@1@_N@Z)`

https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK2019)%26rd%3Dtrue

**Comment by glinscott** [comment]
Should be fixed now, we were missing the NNCache from the project.
