### ISSUE TITLE
Default to a specific filename if -w not specified

### ISSUE THREAD

**Issue by CMCanavessi** [glinscott/leela-chess#129]
Just for easiness of usage when setting up the engine in any UCI GUI, it would be cool if when there's no -w flag, the engine would search for a specific filename like "network" (without extension) instead of exiting and leaving the normal user wondering what's happening.

That way, we can package the binary, the dll, the current network in a 7z and the user will just have to setup the engine in a simple way and everything would work. If the -w is specified, that would override the default network filename.

If this is implemented, added to the recently implemented time control imported from stockfish, I believe the engine would be in a pretty great shape for the end user to start trying and playing tournaments and appearing on rating lists.

**Comment by CMCanavessi** [comment]
Adding a bit of info to this with a real-world case:

Fritz 16 GUI doesn't allow to pass parameters to the .exe file that you select, so right now it's impossible to use lczero.exe with Fritz. Fine I said, I'll make a .bat file with all the stuff there... to my surprise, Fritz ONLY allows you to load .exe files, and will add a .exe to the file if it doesn't have it, for example it will become play.bat.exe

Kinda crappy. We could also use a config file where we specify all the options there.

**Comment by killerducky** [comment]
Default is `weights.txt` if you don't specify `-w` now.
