### ISSUE TITLE
Remove network history

### ISSUE THREAD

**Issue by Error323** [glinscott/leela-chess#13]
The current nn keeps a history of 7 states. We could safely remove it to speed up the network.

**Comment by glinscott** [comment]
@Error323 I'm not sure about this...  I think once we have a version of supervised learning up and running, we can evaluate whether the network with or without history is stronger.  But, the history is a form of an attention mechanism, which might be important for strength.

Also, thinking a bit more about this, how would the network know which positions to avoid repeating without some history?

**Comment by Error323** [comment]
Yeah you are correct. Three-fold repetition is not captured in a chess position. Stockfish computes it from the history as well. In fact, if transpositioning into a state for the third time happens within 50 moves, a draw occurs. So theoretically history should be maintained even longer... The probability of that happening does decrease rapidly though. Still it might be the source of many draw games occuring?

**Comment by will-iam** [comment]
To be sure, we could use a single plane with every single move in the position that draws. It asks to go forward and check every move to put it in a bitboard (this can be computed only if the fiftyrule number is higher enough) but it would remove a huge number of parameters for the history planes and have the whole information about repetition. It's feasible but I have no clue of the result, maybe history planes are still important for other reasons ?
