### ISSUE TITLE
Not sure if uploading is always working.

### ISSUE THREAD

**Issue by jjoshua2** [glinscott/leela-chess#139]
File training.0.gz uploaded successfully with fields user=... is only printing out sometimes.  Other times it skips the whole part with that and the map. Not sure if we a ddos ing the server by running too many clients with multiple folders and stuff, since that windows patch isn't merged yet.

```
PGN
1. d3 b5 2. g4 Bb7 3. Nf3 Nf6 4. g5 b4 5. Nbd2 h6 6. Rg1 hxg5 7. Nxg5 g6 8.
h3 e5 9. b3 Bh6 10. Nde4 d6 11. c3 Nc6 12. Bg2 Na5 13. Ne6 fxe6 14. Rh1
bxc3 15. b4 Bxc1 16. Qxc1 Rb8 17. bxa5 Nxe4 18. Bxe4 Qf6 19. Bxb7 Rxb7 20.
Rb1 Rxb1 21. Qxb1 Ke7 22. Qb4 Rc8 23. Rf1 c2 24. Qc3 a6 25. Kd2 g5 26. d4
exd4 27. Qxc2 c5 28. Qb3 Qf5 29. Qb7+ Kd8 30. a4 Qxh3 31. Rb1 Rc7 32. Qxa6
Qg2 33. Qxd6+ Kc8 34. Qxe6+ Kd8 35. Rb8+ Rc8 36. Rxc8+
END
Score: 1
Created dirs data-1
info depth 17 nodes 1200 nps 729 score cp 3 winrate 50.15% time 1645 pv c2c3 g8f6 g1f3 a7a5
```

It should have:
```END
Score: 1
200
map[Server:[nginx/1.10.3 (Ubuntu)] Date:[Mon, 19 Mar 2018 02:43:35 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[60] Connection:[keep-alive]]
File training.0.gz uploaded successfully with fields user=...
```

**Comment by jjoshua2** [comment]
Maybe we should have retry with exponential backoff? autogtp seems to have that feature where it keeps on trying occasionally, but still keeps on using the last known network to generate more games even if the internet is out for awhile.

**Comment by glinscott** [comment]
Oops, indeed, I don't check the error status from uploading a network!  We should definitely have a retry on this.

**Comment by jjoshua2** [comment]
Created pull for retry with exponential backoff. Could eventually overflow time.sleep possibly? https://github.com/glinscott/leela-chess/pull/153

**Comment by jjoshua2** [comment]
I think this is all fixed now.
