### ISSUE TITLE
Discord server for informal discussions

### ISSUE THREAD

**Issue by Uriopass** [glinscott/leela-chess#144]
Inspired by https://github.com/gcp/leela-zero/issues/913
What about creating a discord channel, for sharing announcment and just for chatting about LZ instead of creating Issues and discussions on the google forum which require big paragraphs and not quick discussion.

I found they were lots of things to chat about on the twitch.tv livestream running against Stockfish lvl 2.
Anyway if anyone wants to join here you go : 
https://discord.gg/pKujYxD

**Comment by glinscott** [comment]
Thanks for setting this up!

**Comment by killerducky** [comment]
There's a link to this on the official page now, join us!  :)
