### ISSUE TITLE
v 0.2 exe is not working

### ISSUE THREAD

**Issue by jimmyai** [glinscott/leela-chess#145]
when i download new exes(0.2), lczero.exe gives me following error that libopenblas.dll is missing, 
and client.exe gives exit status 3221225781.
previous exes are working properly,kindly help me to solve this issue.
TIA. :)

**Comment by jkiliani** [comment]
It appears you still have to get the .dll files from the Leela Zero repository. I thought they would be included in the new release but it seems not.

**Comment by jimmyai** [comment]
:(
kindly any one add dll files in new executable ?

**Comment by jimmyai** [comment]
kindly any one add dll files in new executable !!

**Comment by jkiliani** [comment]
Have you tried getting the .dll's from https://github.com/gcp/leela-zero/releases? I agree they should be part of the release, but they seem to have been overlooked...

**Comment by jimmyai** [comment]
:D  :+1: 
thanks

**Comment by jimmyai** [comment]
now client is running but server is not displaying my user name on active user.?
so is server using my data or not..?

**Comment by Uriopass** [comment]
Have you uploaded at least one game ?

**Comment by jimmyai** [comment]
![image](https://user-images.githubusercontent.com/36767822/37649181-d72c9404-2c52-11e8-9aca-c723854eb32b.png)

**Comment by Uriopass** [comment]
Incorrect password, looks like you already created an account before with a different password. Either change your username or try to remember the password you already set ;-)

**Comment by mooskagh** [comment]
It says "incorrect password".
It should at least exit the process in that case rather than continue calculating and waste it.

**Comment by jimmyai** [comment]
exactly i wanna know the same thing,if the user is not authenticated then how it is generating data,
and server is using unauthorized person's  data or not,because server is not showing it on active users.
:D

**Comment by Uriopass** [comment]
It's generating data (playing a game) because it just needs to download the network for that (no need for user/pass). Then when you upload the generated game it says "incorrect password" and refuses it. Client then continue with execution and generate another game.
So no, the server is not using the unauthorized person's data.

**Comment by jimmyai** [comment]
i am confused because it is actually uploading the data.

**Comment by Uriopass** [comment]
It is uploading the data, but it is not taken into account/deleted by the server. 
Please just change your username or set your good password, your games are simply wasted here.

**Comment by jimmyai** [comment]
yup i just wanna know,
thanks, 
i am now an active user.
:+1:

**Comment by Uriopass** [comment]
Cool :-)

**Comment by jjoshua2** [comment]
It should check the password immediately before downloading network so
com0Ute isn't wasted.

**Comment by Uriopass** [comment]
Yeah I'll see if I can do QoL improvements on the client, like adding multiclient easily too.
