### ISSUE TITLE
Add generation numbers to lczero.org/networks

### ISSUE THREAD

**Issue by sf-x** [glinscott/leela-chess#146]

**Comment by Uriopass** [comment]
I think it was decided to move to sha1 names everywhere.

**Comment by sf-x** [comment]
Has everyone been prohibited to use the generation numbers? ;)

**Comment by jkiliani** [comment]
I think replacing the "ID" column with "gen" or "generation", and counting up from 1 for a490ebcf would work. e49cdc17 and 45bff022 should either be deleted from the page entirely, since these games after all were never used for reinforcement learning, or labeled "-" in the generation column.

If we keep a generation 0, the entry which would make the most sense here would be the rng games generated by @Error323, which are currently not uploaded.

**Comment by jkiliani** [comment]
Hmm since we are using "ID" to identify nets in the match table, this doesn't work unfortunately. But a separate column "gen" only for nets that get promoted to best network should still be ok.

**Comment by glinscott** [comment]
ID is the source of truth for the database, anything else is a bit more work to deal with on the server side.  Hence when I'm putting things together super fast, I just use the easy thing, which is the ID :).

**Comment by sf-x** [comment]
Given that there's now network with an ID which lose the matches and are not promoted, the simple rule "gen = id -4" will break now. Can the "gen" column be added please? From the data used for the graph on main page.

**Comment by CMCanavessi** [comment]
Yeah, now it's a bit ridiculous. In the Matches part you have "ID", then "Candidate ID" and then "Current ID", with some numbers repeating and some skipping a number in between... That's not simple at all.

I think the easiest way would be to just ignore the non promoted networks and just use "Gen X" for the accepted ones. Right now "network id 18" is at the same time "ID 13", Candidate ID 18" and "Current ID 16". Mindblowing :D
Gen 13 just would be plain easier for everyone.

**Comment by mooskagh** [comment]
It would be nice to add support for free-text tags/labels to networks.
GenX would be ones, but I'm sure other tags will be necessary in future.

**Comment by killerducky** [comment]
Looks like the ID naming is defacto standard now instead of GEN naming.
