### ISSUE TITLE
[Critical] Bug in client draw detection, match game end up in infinite loop.

### ISSUE THREAD

**Issue by Uriopass** [glinscott/leela-chess#147]
See 
![image](https://user-images.githubusercontent.com/5420739/37664316-61e58ada-2c5b-11e8-8ad2-1e4347ecaa8f.png)
Probably from 3-fold or no-material detection or 450 move limit problem.

**Comment by jjoshua2** [comment]
Definitely no 3 fold detection. If it doesn't eventually stop there is no 450 limit either, but it could just take a while to get there.

**Comment by jjoshua2** [comment]
I'm not sure my games are uploading, I'm seeing:
```
info depth 12 nodes 800 nps 1441 score cp -2351 winrate  2.62% time 554 pv f4f8 d8f8
bestmove f4f8
info depth 12 nodes 800 nps 6722 score cp 2344 winrate 97.36% time 118 pv d8f8
bestmove d8f8
Unknown command: quit quit
Unknown command: quit quit
Args: [C:\Users\Mark\Downloads\leela-chess/lczero --weights=networks\f393628a290a33e1d041db6751540fd6116982604c63619024206771108e699e -t1 --noise --quiet]
Args: [C:\Users\Mark\Downloads\leela-chess/lczero --weights=networks\6690eba0e0171644f939d36c918bd3a5f9f2e27d2ecf3e132a920a366483c905 -t1 --noise --quiet]
id name lczero
```

**Comment by Uriopass** [comment]
I'm actually sure, I looked at the code and @glinscott did false assumptions about his chess library.
The bug was that the game was thought to be "ended" when n_legal_moves == 0. However this doesn't seem to hold true for https://github.com/notnil/chess

**Comment by jjoshua2** [comment]
On the match game links games thare are draw have no pgn... like: http://lczero.org/match_game/8

**Comment by glinscott** [comment]
Ugh, thanks for fixing this so fast everyone!  Apologies for the inconvenience.  That's the first chess move generator that has returned moves in a drawn position that I've used (and I've used a lot :).
