### ISSUE TITLE
Client v3 compilation problem

### ISSUE THREAD

**Issue by jkiliani** [glinscott/leela-chess#155]
The previous client compiled without problems on my mac, but now I get, on ```go build```:
```
main.go:24:2: cannot find package "github.com/notnil/chess" in any of:
```
Was this dependency not included somehow?

**Comment by cn4750** [comment]
Make sure to read the readme for the client as it has changed too:
[https://github.com/glinscott/leela-chess/blob/master/go/src/client/README.md]()

You are missing a pre-req step.

**Comment by jkiliani** [comment]
OK that helped but it still doesn't compile:
```
./main.go:311:34: too many arguments in call to client.NextGame
	have (*http.Client, string, map[string]string)
	want (*http.Client, string)
./main.go:316:38: nextGame.Params undefined (type client.NextGameResponse has no field or method Params)
./main.go:326:56: nextGame.CandidateSha undefined (type client.NextGameResponse has no field or method CandidateSha)
./main.go:330:72: nextGame.Flip undefined (type client.NextGameResponse has no field or method Flip)
./main.go:331:3: undefined: client.UploadMatchResult
./main.go:331:59: nextGame.MatchGameId undefined (type client.NextGameResponse has no field or method MatchGameId)
```

**Comment by cn4750** [comment]
I don't think you have the latest [http package](https://github.com/glinscott/leela-chess/tree/master/go/src/client/http). Make sure it is up-to-date too.

**Comment by jkiliani** [comment]
OK it was actually solved by the readme... I just exported the PATH, not realising that GOPATH was different.

**Comment by jkiliani** [comment]
Thank you for the assistance 👏

**Comment by martinbel** [comment]
I'm having a similar issue when compiling the client, prior to that it all worked ok. 

```$ echo $GOPATH
/usr/local/go/bin:/mnt/leela-chess/go```

This works ok:
`$ sudo go get -u github.com/notnil/chess`

I get this error: 
```
$ go build
main.go:24:2: cannot find package "github.com/notnil/chess" in any of:
	/usr/lib/go-1.10/src/github.com/notnil/chess (from $GOROOT)
	/usr/local/go/bin/src/github.com/notnil/chess (from $GOPATH)
	/mnt/leela-chess/go/src/github.com/notnil/chess
``` 

I haven't used go so I guess this is probably a basic error. Any ideas?
