### ISSUE TITLE
LCZ almost beats SF 9 level 20 6 ply but loses on time

### ISSUE THREAD

**Issue by jjoshua2** [glinscott/leela-chess#165]
https://lichess.org/wizb3eLn
I've been having lcz consistently lose on the 2nd move due to time using either 2 min or 5 min per move with a 1080ti. 

So cutechess gui lets me add a margin. I tried 50ms and it worked, and 30ms was working for most of this game, but then it didn't. Apparently we need to increase move overhead about 40-50ms or time it more accurately.

**Comment by JackThomson2** [comment]
When I get time I was going to add the UCI options so we can change things like move overhead + time aggressiveness.

**Comment by jhellis3** [comment]
Yeah move overhead can spike quite high (especially on windows).  If playing longer TCs, I would set it to something like 100 - 200ms just to be on the safe side.  Or perhaps we can do this automatically by setting it to 30 + some small % of our total available time up to a max of say 500 ms. If we are getting spikes larger than that, it may indicate an issue worth looking into.

**Comment by jjoshua2** [comment]
I'll just use 50ms margin for now, so there's not a big hurry, but it needs to just work for rating lists and general acceptance. 
Also, the game is worth looking at, using network id 18, about 2 minutes a move, it doesn't seem to make any blunders.
