### ISSUE TITLE
Add a direct link from lczero.org to "Getting Started" document

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#167]
For people who come directly to lczero.org it's still hard to find instructions how to download client and start contributing.

It may make sense to add a link to https://github.com/glinscott/leela-chess/wiki/Getting-Started there.

**Comment by mooskagh** [comment]
And actually also link to discrord would be useful.
So far it's buried somewhere is the middle of old mail thread, isn't it?

**Comment by glinscott** [comment]
Done :).
