### ISSUE TITLE
training or match?

### ISSUE THREAD

**Issue by pw31** [glinscott/leela-chess#172]
Hi there, just a question out of curiosity.  Training is run with current champion, until, at some point, the new network makes a match with current champion. How is it decided when this happens?  From the statistics it seems that about 10000 to 70000 training games are played before a new match starts, which seems not very systematic. Thanks.

**Comment by pw31** [comment]
Thank you!  Is it clear / is there experience from e.g. LeelaZero / has it been tested which is the opitmum number of training games per generation in order to achieve fastest gain of strength per time?

**Comment by CMCanavessi** [comment]
The idea is to be constantly training. 
Training 1 network takes around 4 hours, so while the server is training the network, all the clients train. Then after the network is finished training, the clients download it and play matches. If it passes, then it becomes the new standard network and the clients continue training with that network. Then the server starts training a new net (with the matches that happened while it was training the previous one).
