### ISSUE TITLE
Stats page doesn't get updated when the current network is not the newest

### ISSUE THREAD

**Issue by evalon32** [glinscott/leela-chess#173]
Right now: 07cdce31 and f1f20620 weren't promoted, so games are still played with 38576aeb (~40k as of this writing). But the stats page is stuck at 8454.

**Comment by jkiliani** [comment]
Yes I reported this in #158, along with several other current bugs in the website.

**Comment by glinscott** [comment]
Fixed now :).

**Comment by evalon32** [comment]
@glinscott Are you sure it's fixed? It still seems like the graph is frozen once there's a newer network, even if that network isn't promoted. E.g., right now: 218a136a has 79K games per http://lczero.org/networks, but only 16K games per http://lczero.org/stats.
