### ISSUE TITLE
lczero crashes

### ISSUE THREAD

**Issue by lucasart** [glinscott/leela-chess#177]
* I compiled lczero following the instructions in the readme (on lubuntu 17.10).
* I downloaded the latest client for linux here: https://github.com/glinscott/leela-chess/releases/tag/v0.2
* I run the client (putting it in the build directory where lczero is), but lzcero crashed:
```
lucas@megatron:~/Chess/leela-chess/build$ ./client_linux 
Args: [/home/lucas/Chess/leela-chess/build/lczero --weights=networks/74287cdcfb79a9171fc5c28f2d1d12f7ac4591825dc9b95446533d731485b2a1 -t1 --randomize -n --start=train 15988 1 --quiet]
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
2018/03/24 21:14:11 signal: aborted (core dumped)
```

**Comment by killerducky** [comment]
Maybe a OpenCL problem. What does clinfo say when you run it? 

```
clinfo
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 9.0.282
```

**Comment by zz4032** [comment]
If you have Nvidia graphics, try this.
sudo apt install golang libboost-all-dev zlib1g-dev nvidia-opencl-dev libopenblas-dev

**Comment by lucasart** [comment]
Lookg like I don't have a GPU :(
```
lucas@megatron:~$ clinfo 
Number of platforms                               0
```

**Comment by lucasart** [comment]
OK that worked (CPU instead of GPU). But the NPS is very low on my machine. If fluctuates quite a lot from move to move, but it averages around 600 or so... Is this normal ?

**Comment by jjoshua2** [comment]
600 seems quite high, It seems a i7 6700 is 400+

**Comment by CMCanavessi** [comment]
600 is just a little bit less than what I get with a Radeon R9 380 Nitro. I usually get between 800 and 1k. 

Did you try running several threads at the same time?

**Comment by lucasart** [comment]
is the client not running several threads automatically ?

**Comment by jjoshua2** [comment]
there is a -t option, but I think it is capped at 2 for some reason without changing source...

**Comment by CMCanavessi** [comment]
Can't you just run the client several times and that's it?

**Comment by lucasart** [comment]
Ah, so lame. The threads=1 is hardcoded in the Go client...
https://github.com/glinscott/leela-chess/blob/master/go/src/client/main.go#L128
So I'd have to change that and re-compile

**Comment by lucasart** [comment]
@CMCanavessi: I don't think the program is designed for that. THey'd be running on each other's toes as they write date to the network or data directory.

**Comment by killerducky** [comment]
-t1 in the client is not a bug, it's there for a reason, please don't change it. Instead please run multiple clients.

Yes the program is designed to run the client multiple times, it creates unique dirs.

**Comment by lucasart** [comment]
ok. closing.

**Comment by xoto10** [comment]
> OK that worked (CPU instead of GPU).

@lucasart But what worked? I gather you switched to using a cpu version of lczero instead of gpu ... but how?
