### ISSUE TITLE
How can we use lczero?

### ISSUE THREAD

**Issue by startnoob** [glinscott/leela-chess#178]
I try the shredder and fritz,but they can't accept the options(like -t 2 or -w).What software can uses the lczero?

**Comment by jjoshua2** [comment]
arena and cutechess gui work at least...

**Comment by CheckersGuy** [comment]
It's pretty simple to setup in Arena.

**Comment by Ipmanchess** [comment]
I don't get it run at all
It's not a UCI engine like other engines.. dubble click and it works
I follow get started..put these files in one folder.. click on LCZero ..just a flash screen ,done

even in command prompt..doesn't work..no matter what i try..

Here a screen from latest try: 
https://mega.nz/#!7AQXBbBL!b4VswcXHNh4uh6VST_XT-s1GsbbVfX_prizpRvwCCew

**Comment by erbsenzaehler** [comment]
I think you are using a wrong network file.
Try using "-w network" instead of your "-w latest.txt".

**Comment by CMCanavessi** [comment]
This is exactly why I've been suggesting to make lczero.exe look for a default network name. If -w is specified, then that would override the default.

It would make things way easier for the end user. Just double-click and play.

**Comment by mooskagh** [comment]
It would make sense to add some type of header to networks, that could
include timestamp, for example.
Then lczero could find the latest network to use.

**Comment by Ipmanchess** [comment]
@erbsenzaehler i just follow here: https://github.com/glinscott/leela-chess/wiki/Getting-Started

Using the engine

    To use the engine you need to download one more file, the network weights. These are being updated frequently, download the latest one from the top of the list here:
        http://lczero.org/networks
    Unzip the file and put it in the same folder as lczero.exe. For convience you can rename the file latest.txt.
    Use this command line in your chess GUI, with optional debug log:
        lczero.exe -w latest.txt [-l debug.log]

And i show my screen that i get?

**Comment by killerducky** [comment]
`Unzip the file and put it in the same folder as lczero.exe. For convience you can rename the file latest.txt.`

@lpmanchess judging from the size of latest.txt, I think you skipped the unzip step, and just renamed the file.

**Comment by Ipmanchess** [comment]
@killerducky ..that's the right answer! ;)
 It says download latest network..but Not to unzip it.. we get use too with 7z zip rar files that we know we have to unzip it..but just get network file without a extension and end-user should know this ;)
Maybe a good idea to mark it in getting started!!

Now i will see if i get it installed into FritzGui! 

in command prompt it looks to work now!
C:\Program Files\Chess\Engines\LCZero>lczero -w latest.txt
Generated 1924 moves
Detecting residual layers...v1...64 channels...6 blocks.
Initializing OpenCL.
...

**Comment by killerducky** [comment]
@lpmanchess when I download from http://lczero.org/networks it has a .gz extension. Does it not for you? Also the directions I quoted say to unzip it. Maybe directions on some other page don't mention it? Can you point to which page has incorrect or confusing directions? Then we can try to improve them.

**Comment by Ipmanchess** [comment]
@killerducky you are right..my fault..but i don't see .gz maybe that has confused me..sorry!

**Comment by killerducky** [comment]
Oh if you're in windows it probably hides the .gz extension, but it should show an icon that it's a compressed file. In any case glad it's working for you now.

**Comment by Ipmanchess** [comment]
I get just a blanco icon..nothing it shows that's compressed..but that problem is solved..thanks!

Next..i don't get it loaded into FritzGui (see screen) just blanco.. other engines i get directly the engine name..

https://mega.nz/#!XBQz2KaS!i59Z8QHO4zdGy8BiC5RBTgxvtV2IG_L3Q2YS584xvrE

**Comment by Ipmanchess** [comment]
Same in Cutechess Gui ..doesn't work
it has a command line and tried LCZero\lczero.exe and LCZero\lczero.exe -w latest.txt
Both says Cannot start lczero:

**Comment by pw31** [comment]
Is there a way to use lczero with Scid under Linux? It seems to request an UCI engine with entries "command", "parameter" and "folder".  Are there any pre-compiled executables for Linux? Thanks.

**Comment by erbsenzaehler** [comment]
@Ipmanchess I have it running in cutechess gui
Command is: lczero.exe -t 2 -w get_network --noponder 

Here both the .exe and the weights file are in the same folder. The get_network file is around 50mb in size.

Working directory is the path to the exe.

**Comment by Ipmanchess** [comment]
@erbsenzaehler Thanks for your help!
get_network : 52.595KB
Copy your line and i get this : 
https://mega.nz/#!jUBygD4B!V5sPufmMFfeh7SLMrpKPnfMZv5HhPhyji2kj-BMaiL8

Using Windows 10 Pro

**Comment by mooskagh** [comment]
Try just lczero.exe, not lczero\lczero.exe
Also, are you sure that the filename of the network that you downloaded and unzipped is get_network?

**Comment by Ipmanchess** [comment]
It makes it a lot confusing..when you unzip you get this name to see : 839e5dfb56c06ddb0cc1f817e12fe2e8ca10094ec73ed7fe2e93df945f246b63
so i rename it to get_network ,someone else said call it latest.txt
Can nobody put the right files with one choosen names in one zip file..that end users can just unzip ,click on engine and it works like my other 1000's engines i have here!
To that point i want to go..show to you how people suffer from these things..i'm testing more then 20years engines and i can't even get LCZero starting?
I want to have it in a very simple way..then i can put it on my website for other people who can't find the right way here! Put it on Talkchess with one zip file..click and go for every Gui people using.
The daily updates are not needed..if LCZero is now around 1200Elo ..well creat a package off LCZero 1200 a week or month later you make a LCZero 1500 ..and so on,it will be much easier for end users.
But first it has to be tested on every Gui that people use..
Guys i'm not here to critic..i appriciate the work you do and the help you give..i'm always thinking..how can i make it easy as possible that everyone can enjoy from this very great project!

**Comment by erbsenzaehler** [comment]
@Ipmanchess I agree that lczero needs a bit more time to setup than a regular uci engine right now.

I just had a look at your screenshot and there is a little typo. It has to be "--noponder" with two hyphens instead of just one.

**Comment by Ipmanchess** [comment]
Thanks @erbsenzaehler ..i had see that also..tried but still no go ..tried different ways no luck yet..
