### ISSUE TITLE
Provide filenames for network download link

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#186]
Currently links to network download point to something like:
`http://lczero.org/get_network?sha=a33f1e86fe2ba57db43d8bec69aa7856067eef09d1557a75c7228163027b4eb3`

Which makes them download into filename `get_network`.
It would be nice them to be downloaded into file `a33f1e86fe2ba57db43d8bec69aa7856067eef09d1557a75c7228163027b4eb3.gz` instead

That can be done in multiple ways:

HTML5:
download attrubute of "a" tag:
`<a href="blah" download="a33f1e86fe2ba57db43d8bec69aa7856067eef09d1557a75c7228163027b4eb3.gz">`

HTTP:
in a header:
`Content-Disposition: attachment; filename="a33f1e86fe2ba57db43d8bec69aa7856067eef09d1557a75c7228163027b4eb3.gz"`

**Comment by Uriopass** [comment]
Then just do a pull request ! Easier for gary.

**Comment by CMCanavessi** [comment]
Would also be cool if we could make lczero.exe read the network directly from the .gz

It would add simplicity for the end user, just download and go.

**Comment by glinscott** [comment]
Done by @xoto10!
