### ISSUE TITLE
Leela's tactical skills

### ISSUE THREAD

**Issue by Uriopass** [glinscott/leela-chess#190]
I just downloaded and parsed 120 practice problems from lichess.org, from all different genres (capture the queen, get the advantage, mate in X). Mostly mate problems though.
Everytime, I only asked leela to find the best move (not the best sequence).
This was done using 1000 playouts.
Note that on lichess practice, you have move history. I used this to fill her memory planes.
Here are the results: 

![image](https://user-images.githubusercontent.com/5420739/37956712-63346a5e-31ac-11e8-8025-5a08efc942d3.png)

# Specific results for ID 42
## Puzzles she got right
Expected: e4d6 Leela played: e4d6 -- [link to position](https://lichess.org/analysis/standard/r2qk2r/pp3pbp/1np1p1p1/8/3PN3/Q3P3/PP4PP/R1B2RK1_w_kq_-_2_17)
Expected: g5h3 Leela played: g5h3 -- [link to position](https://lichess.org/analysis/standard/2q3k1/1p1bQ1p1/1p1P1p2/6n1/6p1/6P1/P6P/2R2RK1_b_-_-_3_34)
Expected: c4c5 Leela played: c4c5 -- [link to position](https://lichess.org/analysis/standard/r4rk1/ppp3p1/1b1pN1pp/3P4/2P4B/8/PP3nPP/R3R1K1_w_-_-_0_19)
Expected: e5h8 Leela played: e5h8 -- [link to position](https://lichess.org/analysis/standard/8/8/6pk/4Q2p/2q1P3/6KP/8/8_w_-_-_0_43)
Expected: e7f8n Leela played: e7f8n -- [link to position](https://lichess.org/analysis/standard/5r2/4PB1k/p4pR1/2pP4/8/4n3/q5PP/1r3RK1_w_-_-_1_35)
Expected: g4e5 Leela played: g4e5 -- [link to position](https://lichess.org/analysis/standard/3r2k1/p3Rrpp/1p1p4/n1p2P2/5Bn1/P1P5/2B2P1P/4R1K1_b_-_-_5_26)
Expected: c6d6 Leela played: c6d6 -- [link to position](https://lichess.org/analysis/standard/3r2k1/2R3p1/p1qPpp1p/1pbp4/5PP1/P2P3P/1P2Q1B1/7K_b_-_-_1_31)
Expected: f5d4 Leela played: f5d4 -- [link to position](https://lichess.org/analysis/standard/3k4/5p2/2K4p/2N2np1/1pP5/1Pr2P2/4R1PP/8_b_-_-_12_44)
Expected: d3b3 Leela played: d3b3 -- [link to position](https://lichess.org/analysis/standard/1r1q2k1/R5np/3p1np1/1p1rp3/6B1/3Q2PP/4NP2/3R2K1_w_-_-_0_27)
Expected: e5f7 Leela played: e5f7 -- [link to position](https://lichess.org/analysis/standard/3k3r/ppp3R1/8/3pN3/3P4/P3b3/1P5P/7K_w_-_-_0_35)
Expected: e4f2 Leela played: e4f2 -- [link to position](https://lichess.org/analysis/standard/5r2/p2r1qk1/1p2R2p/3pR1p1/2pPnpQ1/P1P2N1P/1P3PP1/7K_b_-_-_9_35)
Expected: b6d4 Leela played: b6d4 -- [link to position](https://lichess.org/analysis/standard/r1r3k1/3p2bp/pq2p1p1/3bPpN1/1P1P1P2/6P1/3B3P/RN1Q1RK1_b_-_-_0_18)
Expected: e2e1 Leela played: e2e1 -- [link to position](https://lichess.org/analysis/standard/5B1k/1p4pp/5p2/p2Q4/P1p3Pb/2P4q/1P1pr1R1/3R1K2_b_-_-_0_36)
Expected: e1f1 Leela played: e1f1 -- [link to position](https://lichess.org/analysis/standard/3r2k1/ppp2p1p/6p1/8/2P2n2/5P2/P1R2P1P/4rNK1_b_-_-_0_25)
Expected: e6c5 Leela played: e6c5 -- [link to position](https://lichess.org/analysis/standard/8/4k3/R3np1p/4p1p1/4K1P1/7P/5P2/8_b_-_-_1_54)
Expected: d5e7 Leela played: d5e7 -- [link to position](https://lichess.org/analysis/standard/4rrk1/p3b1pn/2qp2bp/3N4/8/8/PP3PPP/R1BQR1K1_w_-_-_0_20)
Expected: b4d3 Leela played: b4d3 -- [link to position](https://lichess.org/analysis/standard/8/3r1k1p/4p3/pp6/1n2P3/1P3PB1/1K4PP/2R5_b_-_-_4_32)
Expected: f5e4 Leela played: f5e4 -- [link to position](https://lichess.org/analysis/standard/1k5r/pp3qp1/1n1p1b2/2pP1b2/2P1NP2/1Q3N2/PP5P/R3R1K1_b_-_-_4_27)
Expected: e5d3 Leela played: e5d3 -- [link to position](https://lichess.org/analysis/standard/r3k1nr/pp3ppp/3qp3/2ppn3/5Q2/2P4P/PP1P1PP1/R1B1KB1R_b_KQkq_-_0_10)
Expected: g3f4 Leela played: g3f4 -- [link to position](https://lichess.org/analysis/standard/2k5/Q1p5/2Pp4/5nNp/6pP/2P3K1/PP4P1/3q4_w_-_-_1_34)
Expected: e2d4 Leela played: e2d4 -- [link to position](https://lichess.org/analysis/standard/8/6p1/8/1p3k2/1P6/2P4P/2r1N1PK/8_w_-_-_5_39)
Expected: f6d7 Leela played: f6d7 -- [link to position](https://lichess.org/analysis/standard/5k2/1pp1bp2/pq2pN1p/4P1p1/8/P4QP1/1Pr2PKP/1R6_w_-_-_2_26)
Expected: d6d1 Leela played: d6d1 -- [link to position](https://lichess.org/analysis/standard/3r2k1/pp3pp1/2nq1np1/2p1p3/2P3P1/P1B1PP2/1PQ3NP/3R2K1_b_-_-_1_20)
Expected: d1e1 Leela played: d1e1 -- [link to position](https://lichess.org/analysis/standard/6k1/p3Bbpp/2p5/PpP5/5R2/4KP2/6PP/3r4_b_-_-_4_33)
Expected: e4f2 Leela played: e4f2 -- [link to position](https://lichess.org/analysis/standard/r5r1/2k2pp1/p4p1p/8/3NnP2/R1PK4/6PP/7R_b_-_-_6_29)
Expected: e7c8 Leela played: e7c8 -- [link to position](https://lichess.org/analysis/standard/2r2k2/1b2Npp1/p6p/1p2b3/1P2p3/P3P2P/5PP1/3R2K1_w_-_-_2_29)
Expected: f3d5 Leela played: f3d5 -- [link to position](https://lichess.org/analysis/standard/4bb2/5k1p/pr4p1/5p2/1P1p4/3P1B2/1P1B1PPP/4R1K1_w_-_-_2_26)
Expected: f5h5 Leela played: f5h5 -- [link to position](https://lichess.org/analysis/standard/r4r1k/p4Pb1/3p4/1p2pQ1p/2p1P3/P2P2q1/BPPBK1Pn/R7_w_-_-_0_23)
Expected: h3g3 Leela played: h3g3 -- [link to position](https://lichess.org/analysis/standard/6q1/7p/2p2p2/1p2r1k1/8/1P5Q/P5P1/7K_w_-_-_0_37)
Expected: d5e4 Leela played: d5e4 -- [link to position](https://lichess.org/analysis/standard/r1bq2k1/pp4pp/2n1p2r/3p4/2P1Q3/B1P1PN2/P4PPP/R2R2K1_b_-_-_0_15)
Expected: d1g4 Leela played: d1g4 -- [link to position](https://lichess.org/analysis/standard/3brrk1/pppq1pp1/2np3p/5N2/4nP2/2N5/PPPB2PP/R2QR1K1_w_-_-_0_15)
Expected: e5d4 Leela played: e5d4 -- [link to position](https://lichess.org/analysis/standard/r4rk1/p4p2/1p3n1p/4q1pb/1N1B4/3B1P2/PP4PP/2RQ1RK1_b_-_-_3_20)
Expected: e8f8 Leela played: e8f8 -- [link to position](https://lichess.org/analysis/standard/4R3/P4k2/7r/2B5/2p4p/2K2b2/6p1/8_w_-_-_4_62)
Expected: e8e7 Leela played: e8e7 -- [link to position](https://lichess.org/analysis/standard/2r1r1k1/1p1bNqp1/1b2pp1p/1P1p4/P1n5/B2BP3/5PPP/1Q1R1RK1_b_-_-_5_24)
Expected: e5d3 Leela played: e5d3 -- [link to position](https://lichess.org/analysis/standard/5r2/p6p/1p3p2/2p1nk2/1P5P/P7/2R5/2K1R3_b_-_-_0_28)
Expected: h4e7 Leela played: h4e7 -- [link to position](https://lichess.org/analysis/standard/r4knQ/1ppn1pr1/p2q4/3P4/P4p1B/7P/1P4P1/2R1R1K1_w_-_-_6_32)
Expected: a1a7 Leela played: a1a7 -- [link to position](https://lichess.org/analysis/standard/8/1k3rpp/1Pp3n1/8/4P3/3P3P/1PP3P1/R6K_w_-_-_1_30)
Expected: a8a1 Leela played: a8a1 -- [link to position](https://lichess.org/analysis/standard/r3r1k1/5pn1/1p1p1q1p/1NpP2p1/1P2P3/3Q3P/5PPB/R3R1K1_b_-_-_0_23)
Expected: b1d1 Leela played: b1d1 -- [link to position](https://lichess.org/analysis/standard/8/4Qp1k/1p1p2pp/8/1P6/1NR5/5PPP/1r1B2K1_b_-_-_1_33)
Expected: a7a1 Leela played: a7a1 -- [link to position](https://lichess.org/analysis/standard/8/r6p/6p1/4p3/1kP1Pn1P/1P1p1PR1/1R1K1P2/8_b_-_-_3_38)
Expected: e1e6 Leela played: e1e6 -- [link to position](https://lichess.org/analysis/standard/r5k1/pp1n1p1p/2p1r1p1/3n2B1/1qB4Q/8/PP3PPP/3RR1K1_w_-_-_0_22)
Expected: g5f6 Leela played: g5f6 -- [link to position](https://lichess.org/analysis/standard/r4rk1/ppp2p2/3p1n2/2b1q1B1/4P3/2p2Q1P/P4PP1/R3R1K1_w_-_-_1_21)
Expected: c3d5 Leela played: c3d5 -- [link to position](https://lichess.org/analysis/standard/R7/p4p2/5k2/8/8/PPN1b3/1Pr5/K7_w_-_-_1_48)
Expected: f5d4 Leela played: f5d4 -- [link to position](https://lichess.org/analysis/standard/8/2b5/2B2kp1/ppP2n1p/3P4/P4KP1/N6P/8_b_-_-_0_39)
Expected: c3d5 Leela played: c3d5 -- [link to position](https://lichess.org/analysis/standard/r4rk1/1bq1bppp/p7/1p1npP2/8/1NNB1Q2/PPP3PP/3R1R1K_w_-_-_0_17)
Expected: g4e6 Leela played: g4e6 -- [link to position](https://lichess.org/analysis/standard/r2q2k1/1b2b1pp/p2p4/2pr4/1p3PB1/4B3/PPPQ3P/2KR3R_w_-_-_0_18)
Expected: g4e3 Leela played: g4e3 -- [link to position](https://lichess.org/analysis/standard/r1bq1rk1/1pp3bp/p2p2p1/3Pp3/2B1P1n1/2P2N1P/PP1N2P1/R2Q1RK1_b_-_-_0_14)
Expected: c2a2 Leela played: c2a2 -- [link to position](https://lichess.org/analysis/standard/6k1/1p4b1/2pN3p/2P1P1p1/3P4/6P1/q1Q4P/rB4K1_w_-_-_6_45)
Expected: d6f7 Leela played: d6f7 -- [link to position](https://lichess.org/analysis/standard/r2k3r/p2nbppp/3N4/3n4/3p4/8/PP3PPP/R1B1K1NR_w_KQ_-_0_15)
Expected: e6e8 Leela played: e6e8 -- [link to position](https://lichess.org/analysis/standard/7k/q2n2pp/p3Qp2/1p1P3R/4P3/1P4PK/r1r4P/7R_w_-_-_4_42)
Expected: f2f4 Leela played: f2f4 -- [link to position](https://lichess.org/analysis/standard/8/3r2pp/pR6/3pkp2/8/r3P1P1/P2R1PKP/8_w_-_-_0_37)
Expected: e5d7 Leela played: e5d7 -- [link to position](https://lichess.org/analysis/standard/5knr/1b3p2/p3pqp1/4N2p/8/2P5/P3QPPP/3R2K1_w_-_-_1_25)
Expected: e7e3 Leela played: e7e3 -- [link to position](https://lichess.org/analysis/standard/5rk1/pp2q3/5p2/5n1Q/1n3P2/1PN1P3/P2K4/R6R_b_-_-_0_28)
Expected: f6g4 Leela played: f6g4 -- [link to position](https://lichess.org/analysis/standard/1k4r1/1pp2p2/3p1n2/PP2p2p/2N1P2P/2PPKPr1/R7/7R_b_-_-_0_29)
Expected: c5e4 Leela played: c5e4 -- [link to position](https://lichess.org/analysis/standard/8/p7/1b1r1k1p/2N5/1P1p2K1/5P2/P2R4/8_w_-_-_6_42)
Expected: d5d3 Leela played: d5d3 -- [link to position](https://lichess.org/analysis/standard/3q2k1/p2r1ppp/1p6/3rB3/8/P2R3P/1P1Q1PP1/3R2K1_b_-_-_0_26)
Expected: h8h2 Leela played: h8h2 -- [link to position](https://lichess.org/analysis/standard/7r/1p2pk2/3p4/p2Pb3/P1P3P1/1P6/2B3K1/4R3_b_-_-_9_41)
Expected: e6d5 Leela played: e6d5 -- [link to position](https://lichess.org/analysis/standard/2rqk2r/3nbpp1/p2pbn1p/1p1Np3/4P3/P2QBN1P/1PP1BPP1/R4RK1_b_k_-_4_13)
Expected: e3e4 Leela played: e3e4 -- [link to position](https://lichess.org/analysis/standard/8/4P3/6q1/7p/7k/3KR2P/8/8_w_-_-_14_59)
Expected: f3a8 Leela played: f3a8 -- [link to position](https://lichess.org/analysis/standard/r2qkb1r/2pb1ppp/4pn2/1N6/pnBP4/4BQ2/PPP3PP/2KR2NR_w_kq_-_2_13)
Expected: e1g1 Leela played: e1g1 -- [link to position](https://lichess.org/analysis/standard/r5k1/p1b5/2p2Pq1/3p4/2p5/4P2P/PP2KQ2/4R3_w_-_-_0_35)
Expected: d1h5 Leela played: d1h5 -- [link to position](https://lichess.org/analysis/standard/rnbqk1nr/pppp4/7p/4N1b1/4Pp2/8/PPPP2P1/RNBQK2R_w_KQ_-_2_9)
Expected: d1h5 Leela played: d1h5 -- [link to position](https://lichess.org/analysis/standard/r1bq1rk1/ppp1bppn/2np4/4p1P1/2P1P3/3P4/PPN2PP1/R1BQKB1R_w_KQ_-_1_10)
Expected: c5a6 Leela played: c5a6 -- [link to position](https://lichess.org/analysis/standard/r1b4r/2q1k1b1/2p1p1np/p1Np1pp1/1BpP4/P3P2P/1PP1NPP1/R2QK2R_w_KQ_-_2_20)
Expected: g2h3 Leela played: g2h3 -- [link to position](https://lichess.org/analysis/standard/6k1/p2r1p2/1p5Q/3pP2K/3PnR2/1P5P/P5q1/8_b_-_-_5_40)
Expected: d3e1 Leela played: d3e1 -- [link to position](https://lichess.org/analysis/standard/8/1p4p1/p1kp1b1p/8/1PP5/P1Nn1RP1/6K1/8_b_-_-_6_39)
Expected: c1c8 Leela played: c1c8 -- [link to position](https://lichess.org/analysis/standard/6k1/3Nbppp/8/1P1b4/8/8/r4PPP/2R3K1_w_-_-_0_25)
Expected: e7f8 Leela played: e7f8 -- [link to position](https://lichess.org/analysis/standard/r1b2r1k/pp1nB1bp/4q1p1/3Np3/8/4P2P/PP3PP1/R2Q1RK1_w_-_-_4_17)
Expected: a7a8 Leela played: a7a8 -- [link to position](https://lichess.org/analysis/standard/6k1/R4pp1/4b2p/2r5/p2p4/3B3P/2P1RPPK/r7_w_-_-_0_31)
Expected: b3f7 Leela played: b3f7 -- [link to position](https://lichess.org/analysis/standard/6k1/1p3pp1/p1bN2q1/4p2p/5n2/PB5P/1P3PP1/3Q2K1_w_-_-_2_32)
Expected: f4f7 Leela played: f4f7 -- [link to position](https://lichess.org/analysis/standard/2rq2k1/3p2pp/p2Np1r1/2p5/3P1Q2/8/PP3PbP/R3R1K1_w_-_-_0_21)
Expected: b5b8 Leela played: b5b8 -- [link to position](https://lichess.org/analysis/standard/1r3r1k/5p1p/p4bp1/1Rp1q3/3p4/5Q1P/P1B2PP1/1R4K1_w_-_-_0_29)
Expected: c7e5 Leela played: c7e5 -- [link to position](https://lichess.org/analysis/standard/1r3r2/p1Q3p1/5k2/2Pp1b1p/3P3P/1P1q1P2/P7/K5R1_w_-_-_5_33)
Expected: e7c5 Leela played: e7c5 -- [link to position](https://lichess.org/analysis/standard/2rq1k1r/1b1pb2p/p4pn1/1p1N3N/3QPp2/2P2B2/PP4PP/R4RK1_b_-_-_0_17)
Expected: e5d7 Leela played: e5d7 -- [link to position](https://lichess.org/analysis/standard/5rk1/1p3ppp/pb6/4N3/1P2pP2/8/4KPPP/2R5_w_-_-_1_26)
Expected: d8a5 Leela played: d8a5 -- [link to position](https://lichess.org/analysis/standard/r1bqkbnr/pp1ppp1p/6p1/1B6/3pP3/3P1Q2/PPP2PPP/RNB1K2R_b_KQkq_-_0_6)
Expected: d7f5 Leela played: d7f5 -- [link to position](https://lichess.org/analysis/standard/r6r/p2Q1ppp/5k2/8/1P4P1/P3p1qP/4B3/3R3K_w_-_-_4_28)
Expected: f6f7 Leela played: f6f7 -- [link to position](https://lichess.org/analysis/standard/r1b1kbnr/pppp1Bp1/5q1p/n7/4P3/1Qp2N2/PP3PPP/RNB2RK1_b_kq_-_0_8)
Expected: g4c8 Leela played: g4c8 -- [link to position](https://lichess.org/analysis/standard/6k1/1p3p1p/2p2Pp1/p3p1P1/4PnQP/2P5/PP3qB1/3r2NK_w_-_-_1_31)
Expected: d4f2 Leela played: d4f2 -- [link to position](https://lichess.org/analysis/standard/3rr1k1/1p3ppn/2ppbb1p/p7/P2BP1Pq/5P1P/1PP1N1QK/1B1RR3_w_-_-_1_25)
Expected: f6h8 Leela played: f6h8 -- [link to position](https://lichess.org/analysis/standard/8/8/5Qpk/5p2/2p5/6PP/p4PK1/1q6_w_-_-_2_46)
Expected: d2d8 Leela played: d2d8 -- [link to position](https://lichess.org/analysis/standard/3rr3/1k4pp/1pp5/5PP1/2P5/4n2P/PP1R4/1K1R4_w_-_-_1_34)
Expected: f4f2 Leela played: f4f2 -- [link to position](https://lichess.org/analysis/standard/8/7k/p5p1/4Nr1p/5q2/3Q4/P1PN1PPP/4R1K1_b_-_-_1_24)
Expected: d7f7 Leela played: d7f7 -- [link to position](https://lichess.org/analysis/standard/6k1/3r3p/2p5/1pPpPK2/pP2p3/P3P2R/6r1/7R_b_-_-_1_39)
Expected: e8d8 Leela played: e8d8 -- [link to position](https://lichess.org/analysis/standard/4r3/pk6/1p4p1/2pN3p/P6P/5PP1/1B3K2/8_b_-_-_1_33)
Expected: b4e4 Leela played: b4e4 -- [link to position](https://lichess.org/analysis/standard/4kbnr/4pp1p/2p3p1/4B3/1r6/1P6/P4PPP/RN2K2R_b_KQk_-_1_18)
Expected: h6h8 Leela played: h6h8 -- [link to position](https://lichess.org/analysis/standard/r3k3/pp4r1/4p1bR/3pp3/8/2P3N1/PP3PP1/R3K3_w_Qq_-_0_22)
Expected: d6e5 Leela played: d6e5 -- [link to position](https://lichess.org/analysis/standard/5rk1/R5pp/1p1qb3/3pN3/1b1Np3/4P2P/4QPP1/6K1_b_-_-_0_24)
Expected: d4e2 Leela played: d4e2 -- [link to position](https://lichess.org/analysis/standard/rn1q1rk1/2p2p2/p3p2p/1p2P1PN/3nN3/5PQ1/PP4P1/R4RK1_b_-_-_0_23)
Expected: e2b5 Leela played: e2b5 -- [link to position](https://lichess.org/analysis/standard/r3kq1r/1b3Np1/np2Pp2/p2p1p2/3P4/2P1B3/P3QPPP/R4RK1_w_kq_-_3_21)
Expected: h1h2 Leela played: h1h2 -- [link to position](https://lichess.org/analysis/standard/5r1k/2R2p1p/3p4/3Ppq2/5n2/5QP1/7r/2R2B1K_w_-_-_0_30)
Expected: e4d2 Leela played: e4d2 -- [link to position](https://lichess.org/analysis/standard/6k1/p4p1p/1p4p1/8/4nP2/R4K2/P1r3PP/1R6_b_-_-_5_29)
Expected: e5e6 Leela played: e5e6 -- [link to position](https://lichess.org/analysis/standard/8/pp2r1pp/2p1bk2/4Rp2/2P2P2/1P3BP1/P3RK1P/3r4_w_-_-_11_29)
Expected: c7e6 Leela played: c7e6 -- [link to position](https://lichess.org/analysis/standard/3b4/2N4p/2b3p1/p1k1p3/1p2P1P1/1P1K3P/P5B1/8_w_-_-_20_47)
Expected: c1c8 Leela played: c1c8 -- [link to position](https://lichess.org/analysis/standard/2b1k2r/p4p2/1p1Pp2p/3p4/8/PP2n2P/5PPK/1BR5_w_k_-_0_31)
Expected: g6b1 Leela played: g6b1 -- [link to position](https://lichess.org/analysis/standard/8/pp1Q3p/6qk/3P4/8/P4B2/1P4PP/7K_b_-_-_0_41)
Expected: d3c4 Leela played: d3c4 -- [link to position](https://lichess.org/analysis/standard/rnbq1rk1/ppp3pp/3p1p2/5p2/1b1P4/2NQ4/PPP1PPPP/2KR1BNR_w_-_-_2_7)
Expected: e2e8 Leela played: e2e8 -- [link to position](https://lichess.org/analysis/standard/r3r1k1/ppp2pbp/2n5/3q1bB1/2pp4/5N2/PPPNQPPP/R3R1K1_w_-_-_8_13)
Expected: e7g5 Leela played: e7g5 -- [link to position](https://lichess.org/analysis/standard/r4rk1/1b2qppp/2p1p3/pp1n3N/P2PQ3/1B1R4/1PP2PPP/2K4R_b_-_-_2_16)
Expected: f1e2 Leela played: f1e2 -- [link to position](https://lichess.org/analysis/standard/r1b1k2r/pppp1ppp/8/2b5/3P1Pn1/8/PPP1q1PP/RNB1KB1R_w_KQkq_-_0_10)
Expected: c3b2 Leela played: c3b2 -- [link to position](https://lichess.org/analysis/standard/6k1/5p1p/5Bp1/pN2Pp2/1b3P2/1PK3P1/b6P/8_w_-_-_2_38)
Expected: b4b2 Leela played: b4b2 -- [link to position](https://lichess.org/analysis/standard/1k1r1b1r/pp2pQ1p/4P1p1/3p2B1/1q6/P1R5/1PP3PP/R6K_b_-_-_0_21)
## Puzzles she failed
Expected: f3f2 Leela played: f3f8 -- [link to position](https://lichess.org/analysis/standard/5B1k/p1Q3pp/8/7q/2PP2n1/1P3rP1/P3R1KP/3R4_b_-_-_0_33)
Expected: e4d5 Leela played: c5c4 -- [link to position](https://lichess.org/analysis/standard/5qk1/p5pp/8/2Q5/4B3/Pr4PP/5P1K/8_w_-_-_1_40)
Expected: b3f7 Leela played: d1h5 -- [link to position](https://lichess.org/analysis/standard/r1bqkb1r/2p1n1pp/p7/np2p3/4P3/1B6/PPP2PPP/RNBQR1K1_w_kq_-_0_11)
Expected: h6g7 Leela played: d5e4 -- [link to position](https://lichess.org/analysis/standard/6rk/7p/p4p1B/P2QnN2/4p3/7P/5qPK/8_w_-_-_3_40)
Expected: e5c6 Leela played: e4d6 -- [link to position](https://lichess.org/analysis/standard/2q3k1/r2nbppp/p3b3/1pp1N3/4NQ2/5B2/PPP2PPP/3R2K1_w_-_-_1_21)
Expected: e5c6 Leela played: e5d3 -- [link to position](https://lichess.org/analysis/standard/2r3k1/6pp/8/4N3/1q1p3n/8/3R2PP/4Q1K1_w_-_-_16_39)
Expected: e5d3 Leela played: b3b4 -- [link to position](https://lichess.org/analysis/standard/r2r4/1p2kpp1/pP2p1p1/P1qpN2n/Q4P1P/1RN2Rn1/2P2P2/6K1_w_-_-_0_28)
Expected: c6e7 Leela played: g2g4 -- [link to position](https://lichess.org/analysis/standard/2r3k1/2r1pp1p/pqNp2p1/1p1Pb3/1P2P3/1Q2P3/P1R3PP/5RK1_w_-_-_4_22)
Expected: d6h2 Leela played: d6b4 -- [link to position](https://lichess.org/analysis/standard/5rk1/pp4pp/3bp3/8/8/1P2P3/PB1P2PP/5RK1_b_-_-_1_20)
Expected: e1e5 Leela played: g3g5 -- [link to position](https://lichess.org/analysis/standard/r4rk1/5q2/pp1p2p1/2pNbb2/2P5/6QP/P2B2P1/4RR1K_w_-_-_4_23)
Expected: d4d1 Leela played: f1a1 -- [link to position](https://lichess.org/analysis/standard/8/1p5p/p7/4r3/3Rb1P1/1pP3KP/1P2k3/5R2_w_-_-_13_37)
Expected: h8h1 Leela played: f6h4 -- [link to position](https://lichess.org/analysis/standard/r1b4r/3pkpp1/p3pq2/1pp5/4PP2/P2P2p1/BPPQN1P1/R4RK1_b_-_-_1_18)
Expected: c5b7 Leela played: e1c1 -- [link to position](https://lichess.org/analysis/standard/1k1r3r/ppp2pb1/2nqp2p/1BNp2p1/Q2P4/P1P1P1P1/1P1N1P2/R3K2b_w_Q_-_0_21)
Expected: f5g4 Leela played: c8d7 -- [link to position](https://lichess.org/analysis/standard/r1b2nk1/2q2rp1/p3p2p/Pp1pPp1P/1P1P1NP1/2pQ1B1R/2P1KP2/R7_b_-_-_1_22)
Expected: e6c4 Leela played: b2b5 -- [link to position](https://lichess.org/analysis/standard/N7/3k1pR1/p1p1bB2/4p3/4P2P/2PK4/1q6/6R1_b_-_-_6_34)
Expected: b3a4 Leela played: d3c4 -- [link to position](https://lichess.org/analysis/standard/r3k2r/ppp2ppp/1b1p1q2/4P3/2b2P2/1Q1PpN2/PPP3PP/R4R1K_w_kq_-_0_15)
Expected: f2f5 Leela played: h7h5 -- [link to position](https://lichess.org/analysis/standard/N6k/1Q3p1p/p5p1/8/1P1b2K1/3P2P1/P1P2q1P/1R4n1_b_-_-_3_31)
Expected: b4e1 Leela played: b4c3 -- [link to position](https://lichess.org/analysis/standard/4k3/Q2p1p1p/B1r1p3/4P1P1/1q5P/6P1/P1P5/R1K5_b_-_-_0_28)
Expected: g6f7 Leela played: f1f7 -- [link to position](https://lichess.org/analysis/standard/r1b2b2/1p2k3/p3p1Q1/8/2pP3P/2P3B1/PP2p1q1/2KR1R2_w_-_-_4_29)

**Comment by CMCanavessi** [comment]
That's not bad at all, I expected it to do much worse.

**Comment by evalon32** [comment]
Nice! Some of the "fails" are going to be "mate in X" where Leela instead finds a mate in Y. (For example, the last one: X=2, Y=4.) Since Leela isn't rewarded for finding the shortest mate, I'd question whether it's even a fair standard. I guess this is the chess equivalent of winning by small margins.

**Comment by CheckersGuy** [comment]
Would like to see how her tactical strength compares to previous versions

**Comment by Uriopass** [comment]
@evalon32 I'll check, maybe the puzzle contains this information (they are just big JSON with tons of things)
@CheckersGuy I'll run older IDs on theses to see !

**Comment by pw31** [comment]
looks like we need more difficult puzzles ...  :-)

**Comment by jhellis3** [comment]
Here is test set of tricky mates I sometimes use, some of the later ones will be far too deep to solve in reasonable time though.
https://www.dropbox.com/s/i13eu86tcgiqgmn/toughmates.fen?dl=1

**Comment by Uriopass** [comment]
Please note that Leela Zero *needs* the 7 preceding moves, I can't just fill em with zeros or she'll think it's the opening or something. Most puzzles are done from a single position because nobody usually needs the 7 move history planes, so for the moment the only source I found which has practice problems *and* history is lichess..

**Comment by jhellis3** [comment]
Ah well, was the wrong file anyway.

**Comment by lightvector** [comment]
@Uriopass or anyone else - for the training, have you considered randomly on 5% of the training examples giving Leela Zero randomly only 0 to 6 of the preceding moves by zeroing out the other planes?

I believe this should make the neural net capable of behaving reasonably on positions without history because it will want to also make good predictions on that 5%, yet with only minimal cost to the learning in the common case where history exists because 95% of the data will be as before and be by far the dominant component in the loss.

As Leela Zero Chess becomes strong, this would have the great benefit for users who want to set up and analyze arbitrary positions, or ask "what if" by changing pieces around in a position, without always having to supply a long plausible history to reach that position.

**Comment by jhellis3** [comment]
From what I have seen thus far, history does not have much of an impact on the eval anyway.  Of course, that may change....

**Comment by evalon32** [comment]
Related: I just gave Leela the [Bratko-Kopec Test](https://chessprogramming.wikispaces.com/Bratko-Kopec%20Test). With the ID67 network, running on a 1080Ti, it scored 12 out of 24, which is supposed to correspond to ELO 2000-2199 (but does it? seems too high). Positions solved correctly after 120 sec: 1,2,3,4,7,8,11,12,14,17,19,22.

**Comment by Uriopass** [comment]
Yeah but it didn't have history, so it's not really "normal" conditions.. I think I'm going to test with and without history to see how much this plays to solve problems like this.
