### ISSUE TITLE
super-short games -> "Stats" graphs

### ISSUE THREAD

**Issue by pw31** [glinscott/leela-chess#195]
I wonder whether I understand the "Stats" graph from http://lczero.org/stats correctly.  It seems to show a handfull of games, for each network, finished as early as move 5 or so - is that true even now where LCzero is ~ 1800 ELO?  Would it be possible to add the number of moves made to e.g. http://lczero.org/match/42 to checkout those games?

**Comment by Error323** [comment]
Hi @pw31,

The stats are generated from the traininggames. The traininggames contain a lot of randomness, hence there are short games in there. The matchgames do not contain this high level of randomness, but are not contained within those stats.
