### ISSUE TITLE
next behind master

### ISSUE THREAD

**Issue by killerducky** [glinscott/leela-chess#206]
I think this fix:
Edit: https://github.com/glinscott/leela-chess/commit/e269323b24dfaf329a3999a84e38ba3b101d6879

Was added to master only, not next. I usually compile and run from next only to have the latest code, so I think this could be a problem?

**Comment by killerducky** [comment]
I originally linked the wrong thing. Edited in OP.

**Comment by Error323** [comment]
@glinscott could you try to find a way we can disable pushing to master directly? We should always merge into master through branches and assign a tag IMO.
