### ISSUE TITLE
Huge draw percentage increase? (possible 3-fold problem)

### ISSUE THREAD

**Issue by rwbc** [glinscott/leela-chess#209]
I noticed from the stats `http://162.217.248.187/stats` that the current ID has a much higher draw percentage now.
From the graph it can be easily seen it comes from an extremely high rise of three fold repetitions.
Is this something we can explain or being expected?

**Comment by jkiliani** [comment]
From what I could see, many of the three-folds are from bugged games (client version 3 with Id 55 network). When version 4 is enforced, hopefully very soon, and a new net promoted, the draw rate should be going back down again.

**Comment by Dorus** [comment]
if the problem is that big, why not stop using client 3 games in training right now, and enforce updates right now? I know v0.4 was released very recent (18h ago), but if those games are useless anyway it's a waste of resources to keep them going. Most people will update very soon anyway.

**Comment by jkiliani** [comment]
I also thought that the games were probably useless, but they were used anyway now, and at least it appears to have done no harm. It is a waste of resources though to produce games so clearly below the net's potential, agreed.
