### ISSUE TITLE
Raw training data

### ISSUE THREAD

**Issue by Tilps** [glinscott/leela-chess#216]
Over on Leela zero they have a place that hosts all the training data in large zip files to download.  I was interested in looking at doing some analysis on the training data for leela chess, but so far I've only found the ability to get the pgn per game from the server, not the training data. Have I overlooked something?  If not, would it be possible to make this data available?

**Comment by Error323** [comment]
See lczero.org for all your data requirements.

**Comment by Tilps** [comment]
Thankyou!
