### ISSUE TITLE
Improve UCI compatibility

### ISSUE THREAD

**Issue by killerducky** [glinscott/leela-chess#218]
Just opening an issue to track this so I can refer to it in some pulls I'm doing. I don't think we need to do anything right away, but over time hopefully we can improve things.
http://wbec-ridderkerk.nl/html/UCIProtocol.html -- I've been referring to this.

There are a few things LCZero does that are not UCI compliant. You're supposed to be ready to answer the initial UCI command instantly, some GUIs don't work because we are too slow to respond initially, especially if tuning is happening. I thought I saw when you're allowed to do slow initialization operations but I can't find it now... 

We're supposed to support option/setoption instead of relying on command line switches. Some GUIs don't even allow you to pass command line switches to the engine. For weights I think it makes sense to have a default name such as "default_weights.txt", along with an option that allows you to change it using UCI commands.

The go and ponder commands are asynchronous, the GUI can send additional commands while the search is going on.

**Comment by Akababa** [comment]
It's isready for initialization

**Comment by killerducky** [comment]
Obsolete LCZero issue.
