### ISSUE TITLE
Maintain an up-to-date readable README?

### ISSUE THREAD

**Issue by reppolice** [glinscott/leela-chess#224]
Hi,

I have spent quite some time with the papers and the code over the last 6 months, and I am still unsure about loads of things happening in the project. Luckily participation is easy, but things like the batching of the games for upload (how many, how often), the "resumability" of the work or if work gets "lost" if stopped before the upload, the very different statistics for the networks, how do we move from one generation to the next. I think you get my point, if someone who knows all of that stuff could condense them in the README for the end user, perhaps with some extra commentary like "we may have a bug in this part" or "we expect to see a preference for the Queen's Indian like AlphaZero in about 2 months at current rate of participation", such a write up would help me a lot and could enlighten many of the volunteers too. Amazing work anyway, a simple concept that actually has so many moving parts!

**Comment by killerducky** [comment]
We have a wiki that anyone can edit, and READMEs for the code that anyone can do PRs for. Please feel free to help out.
