### ISSUE TITLE
Show actual move played during self-play

### ISSUE THREAD

**Issue by Uriopass** [glinscott/leela-chess#227]
I wanted to write a GUI on top of the client so that you can see the self-play game unfold live. However after experimenting and reading the code a bit, the best you can obtain is the PV after 800 nodes, which corresponds to the bestmove leela thinks, but not what she will actually play (since t=1 in self-play games). 

The move played should be printed in a way, probably by doing `myprintf_so("move played %s\n", UCI::move(move).c_str());` at https://github.com/glinscott/leela-chess/blob/master/src/UCI.cpp#L149

However I'm not very familiar with the C++ codebase, so I don't know if it is the best place to do this.

**Comment by killerducky** [comment]
It's printed as `bestmove` here:
https://github.com/glinscott/leela-chess/blob/0cb27d5de925c65bfd29df5c906b22cf94e319c2/src/UCI.cpp#L116

**Comment by Uriopass** [comment]
This is when you use "go", self-play games do not use this function. Look at my link.
