### ISSUE TITLE
Training data download not working

### ISSUE THREAD

**Issue by nousian** [glinscott/leela-chess#233]
Trying to download training data, helping to setup training HW. However, I get "Access denied" both with browser and curl:

_curl https://s3.amazonaws.com/lczero/training/games1980000.tar.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9437B3E59CA6FB0D</RequestId><HostId>qKKeqFDtu3C7mvMczlmfvoLq/Ywur5mgXOzvkc/9rCOBjO+Lyn8b+BtQlMO3/Q8ra3CGiciuOV0=</HostId></Error>_

And browser:

_https://s3.amazonaws.com/lczero/training/games1880000.tar.gz
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8AAECB7A73F69A86</RequestId>
<HostId>
k7w28bvGECmNUDNJMnbuQDNnByfIvtuzIGhq+Hqo9FJIZrxKcAMPW9YJqpDpz5qLXbPasPjo5YE=
</HostId>
</Error>_

Am I missing something, do I need to apply for credentials?

**Comment by jkiliani** [comment]
The new training data was apparently not set to automatically get read access by @Gary, https://s3.amazonaws.com/lczero/training/games1760000.tar.gz is the last accessible archive. There's a discussion in the Discord dev channel about that.

**Comment by nousian** [comment]
Ok, I will download from there downwards.

**Comment by nousian** [comment]
Transfer going fine, any suggestion how to fix and/or get the newer than https://s3.amazonaws.com/lczero/training/games1760000.tar.gz batches? 

I guess we just have to wait for @glinscott to grant read access, not much else we can do?

**Comment by nousian** [comment]
Gary - Today at 6:12 PM:
_all the training data links have been fixed now_
