### ISSUE TITLE
Double PGNs Uploaded During Training

### ISSUE THREAD

**Issue by cn4750** [glinscott/leela-chess#238]
[http://lczero.org/game/2189826](http://lczero.org/game/2189826)
PgnViewer: Error parsing:e4, no candidate pieces for: e4

`
new PgnViewer(
  { boardName: "training",
    pgnString: '1. d4 g6 2. e4 a5 3. h3 Bg7 4. Nf3 d6 5. Nc3 Nd7 6. Be2 Ngf6 7. e5 Nh5 8.\ng4 Nhf6 9. exf6 Nxf6 10. a3 c6 11. a4 O-O 12. Be3 Nd5 13. Nxd5 cxd5 14. c3\ne6 15. h4 f5 16. gxf5 exf5 17. b3 f4 18. Bd2 Qe7 19. h5 g5 20. Rg1 g4 21.\nNh2 g3 22. fxg3 Bh3 23. Nf3 Rae8 24. gxf4 Kh8 25. Ng5 Bf5 26. Kf2 Be4 27.\nBb5 Rc8 28. Nxe4 Qxe4 29. Be2 Qxd4\x2b 30. cxd4 Bxd4\x2b 31. Kf1 Bf2 32. Bg4 Bxg1\n33. Rc1 Rxc1 34. Bxc1 Bc5 35. Be6 d4 36. f5 d3 37. Bb2\x2b Rf6 38. Bxf6\x2b \n1. e4 b6 2. Nf3 b5 3. g3 Bb7 4. d4 Bxe4 5. Bg2 Bb7 6. a4 a5 7. axb5 Nf6 8.\nc4 Rg8 9. Nc3 e6 10. d5 Na6 11. O-O Be7 12. bxa6 Bxa6 13. Ne5 Rc8 14. Qd3\nBb4 15. Bg5 h6 16. Bf4 g5 17. Be3 Ra8 18. Nd1 d6 19. Nc6 Qc8 20. f4 Nxd5\n21. Qh7 Rf8 22. cxd5 Bxf1 23. Kxf1 Qa6\x2b 24. Kf2 gxf4 25. gxf4 Qxc6 26. dxc6\nRc8 27. Qe4 d5 28. Qf3 d4 29. Bxd4 f6 30. Qg4 Ke7 31. Ne3 Rfd8 32. Qg7\x2b Kd6\n33. Bf1 Rg8 34. Qd7\x2b \n',
    pieceSet: 'merida',
    pieceSize: 55
  }
);
`

[http://lczero.org/game/2198808](http://lczero.org/game/2198808) too.

**Comment by killerducky** [comment]
See also #237.
