### ISSUE TITLE
Running leela-chess

### ISSUE THREAD

**Issue by lepetitmoulin** [glinscott/leela-chess#253]
I seem to be having an issue running the leela-chess file, and I am unsure as to how actually to extract the data it's producing in the terminal.

I have followed the instructions in the wiki, and when I try to execute chmod +x client_mac && ./client_mac in the Terminal, it starts spitting out "info . . . " followed by some groupings of numbers and letters.

However, if I try to run either the lczero or client_mac exes via the classic double-click method, neither one can successfully run . . . lczero says it needs network weights (which I downloaded and put into the same folder) and client_mac tells me Error decoding JSON EOF.

Any fixes? Thanks

**Comment by Uriopass** [comment]
You are not good to go, this is running lczero not the client, you won't help to contribute with this.

**Comment by Uriopass** [comment]
Also @lepetitmoulin since I solved your issue on the discord, that'd be great if you could close this issue !
