### ISSUE TITLE
define cpu threads

### ISSUE THREAD

**Issue by hurnhu** [glinscott/leela-chess#256]
is it possible to define the # of cpu threads used?
as or right now its only using 1 of 8, i want it to use all 8

**Comment by CMCanavessi** [comment]
For the client, just run it 8 times.

For the engine, you can specify -t 8 or --threads=8 arguments

**Comment by hurnhu** [comment]
nevermind this im going to be making a pr soon that adds the ards --threads so you can define it yourself

**Comment by jjoshua2** [comment]
#201 Gary said training might not work with multiple threads...
