### ISSUE TITLE
Stuck at `Detecting residual layers...v1...64 channels...6 blocks.` in Mac

### ISSUE THREAD

**Issue by duplex143** [glinscott/leela-chess#259]
After executing `./lczero -w latest.txt`, I'm stuck at `Detecting residual layers...v1...64 channels...6 blocks.` . Nothing is happening after this.

**Comment by Uriopass** [comment]
For simple questions and need for help, please come to the [discord](https://discord.gg/pKujYxD). I will help you there.

**Comment by duplex143** [comment]
Got help via discord from @Uriopass
