### ISSUE TITLE
Port NNCache over?

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#26]
This was a significant speed-win for Leela-zero.  I haven't measured how many duplicate eval calls we make though.

**Comment by gcp** [comment]
Note that NNCache may become a bit more redundant if search tree reuse is implemented. There is a proposal which will probably be merged with changes: https://github.com/gcp/leela-zero/pull/632

**Comment by gcp** [comment]
Tree reuse is now merged upstream. It's a fairly large gain at a fixed number of playouts, but it does reduce the effectiveness of the NNCache. I think the latter is now only useful when analyzing games (still a pretty common use case!).

**Comment by glinscott** [comment]
@gcp thanks, will look at porting it over.

**Comment by Error323** [comment]
@killerducky would you like to implement this?

**Comment by Error323** [comment]
Oh sorry am on phone. I ment tree reuse mostly. But this is also good ofc :)

**Comment by killerducky** [comment]
I might get some time to work on tree reuse this weekend.
