### ISSUE TITLE
can anyone help me do a net2net to a 40block?

### ISSUE THREAD

**Issue by hydrogenpi** [glinscott/leela-chess#260]
can anyone help me do a net2net to a 40block?

**Comment by davidxu90** [comment]
A 40-block net is even larger than the architecture DeepMind used for AlphaZero, and as such would massively slow down the training process. Moreover, there's no sign that the current 6-block net has reached its saturation point, and even if it has, it's preferable to upgrade in small increments rather than immediately jump in network size.

Unless of course you simply want a 40-block net for your personal use, in which case... what do you need help with?

**Comment by hydrogenpi** [comment]
@davidxu90 thanks for the response. I should clarify that currently the LZ (not the chess variant) is already on 10 block and they are debating going to 20 blocks within the next few days/weeks for sure. So a 40 block is not that out of the realm of do-ability. 

For self playing games you are right that 40b is WAY too slow and would never work, since unlike CHess, Go is far less popular it seems and they only got like 200 clients at any given moment and this hardly is enough compute power for 20 block and 40b is out of the question.

Some folks have created a 20 block and trained with 1.5 Million games of using the training set and purely from supervised learning was able to get it to be far stronger than the best/latest 10 block reinforced network. 

Given that in the next few years GPU is expected to leap frog what is available today in terms of the gtx1080ti, I do see at the high end that a custom 40 block might make sense. esp if used for test or pro matches where people typically rent out hardware from a VPS or like on azure, gcp, or aws, since they all offer the likes of 8x V100 nowadays for rent etc... 

So yes I want to create a 40 block for personal use, I don't expect it ever to be used in reinforcement training, just supervised learning. A net2net of the latest 10block (network number 116) to a 40 block 256 filters arch, and then using the latest self-played games (training data available online) to train with many steps and on high end hardware I'm pretty sure it will be stronger than the 20 blocks that exists right now... (and the 20 blocks themselves are already stronger than the 10 blocks).

I need help with getting Tensorflow to work on the windows server I'm using, and doing the net2net and starting the process of the training. I contacted this guy the OP here ( https://github.com/gcp/leela-zero/issues/1113 ) but because phisolophicall he did not agree with testing a 40 block  he refused to help me even when I offered to compensate for his time and efforts.  The 20 block he trained was also on very old network (78 from months ago!) and he didn't even trained the last 1 million games or so!!!! 

Basically I have zero linux skills, and I also get errors with Tensorflow in Windows. So I'm not sure how to do the net2net, and once that is done, I'm not sure how to get the supervised learning process started. 

I came across this document but its in Chiense and Google translate doesn't work that well..
https://github.com/pangafu/LeelaMasterWeight/blob/master/How_to_Training_Yourself_Weight(CN).docx

here is the training data:
https://github.com/gcp/leela-zero/issues/167

and the net2net:

https://github.com/gcp/leela-zero/blob/master/training/tf/net2net.py

Because training takes weeks, I ddin't want to go on the wrong path and start and then weeks later realize I missed a step. I've never trained a net before but really want to do a personal 40b for my own use. 

For reference, the guy who already did the net2net from 10b 128filters to 20block 256 filters:
https://github.com/gcp/leela-zero/issues/1113

can you help me with this

**Comment by Marcin1960** [comment]
Ask Google, they might help you ;)

**Comment by killerducky** [comment]
Please do not use the leela-chess issues as a job request board for leela(Go) help.
