### ISSUE TITLE
Node mutex size

### ISSUE THREAD

**Issue by gcp** [glinscott/leela-chess#27]
https://github.com/glinscott/leela-chess/blob/9b1e319eda079b66bf9b742ed5005877ade1e541/src/UCTNode.h#L85

Please note:
https://github.com/gcp/leela-zero/commit/2665d2db7fbcb12ea7ce1abee6740fa4ed67d1ea

Another proposed solution was to use hashed mutexes, but IMHO those make everything very complicated, and simple per node mutexes are only a byte(!).

**Comment by glinscott** [comment]
@gcp yes, I should move this back.  The issue I saw was when running under tsan, it was giving me a bunch of data race errors.  So I put the mutex in place to make 100% sure I didn't have any threading errors.  At this point, it is tsan clean, so can look at moving back to a spinlock.

**Comment by gcp** [comment]
I think that happens if your TSAN is not fully compatible with your C++ library's implementation of atomics. I remember having similar issues, but the one on macOS was compatible and I used that to make Leela Zero TSAN clean.

**Comment by glinscott** [comment]
Done in 3456912656ee9c0351235db4e1b08a7cab7ad3b8
