### ISSUE TITLE
Increase network size

### ISSUE THREAD

**Issue by bastiaf** [glinscott/leela-chess#282]
There is no progress since 1.5M games which is 1/3 of all games played. I think this is a lot of lost resources, and in the longer run it will demotivate users. Why isn't the network size increased, to 10x128 or something like that? It seems to be a good time now. Isn't it?

**Comment by glinscott** [comment]
There has been a ton of progress.  The graph is not representative unfortunately...  There is a ton of work happening to fix some bugs and potentially increase network size.
