### ISSUE TITLE
v0.5 produces different move from v0.4 with --threads=1 on CPU

### ISSUE THREAD

**Issue by Aloril** [glinscott/leela-chess#289]
./lczero_0_4 --threads=1 --visits=10 --weights=id106 --seed=1
Using 1 thread(s).
RNG seed from cli: 1
Generated 1924 moves
Detecting residual layers...v1...64 channels...6 blocks.
BLAS Core: Nehalem
position fen r1bqkbnr/pp1ppppp/2n5/2p5/P1P5/8/1P1PPPPP/RNBQKBNR w KQkq - 0 1 moves d2d3 g8f6 g1f3
go
update_root, 0 -> 0 expanded nodes (0.0% reused)
NNCache: 0/0 hits/lookups = 0.0% hitrate, 0 inserts, 0 size
info depth 6 nodes 2 nps 42 score cp 3 winrate 50.97% time 23 pv e7e5 b1c3
info depth 7 nodes 3 nps 47 score cp 7 winrate 52.07% time 42 pv g7g6 g2g3
info depth 8 nodes 4 nps 56 score cp 5 winrate 51.65% time 53 pv e7e5 b1c3 f8e7
info depth 9 nodes 7 nps 68 score cp 4 winrate 51.24% time 87 pv g7g6 g2g3 f8g7

g7g6 ->       3 (V: 52.22%) (N: 22.44%) PV: g7g6 g2g3 f8g7 f1g2
e7e5 ->       3 (V: 50.72%) (N: 25.29%) PV: e7e5 e2e4 d7d6
d7d5 ->       2 (V: 49.25%) (N: 15.00%) PV: d7d5 c4d5 f6d5
e7e6 ->       1 (V: 50.94%) (N: 14.23%) PV: e7e6 e2e4
h7h6 ->       0 (V: 49.18%) (N:  5.00%) PV: h7h6 
d7d6 ->       0 (V: 49.18%) (N:  3.95%) PV: d7d6 
a7a6 ->       0 (V: 49.18%) (N:  2.46%) PV: a7a6 
a7a5 ->       0 (V: 49.18%) (N:  1.81%) PV: a7a5 
h7h5 ->       0 (V: 49.18%) (N:  1.11%) PV: h7h5 
a8b8 ->       0 (V: 49.18%) (N:  1.03%) PV: a8b8 
f6g4 ->       0 (V: 49.18%) (N:  0.79%) PV: f6g4 
b7b6 ->       0 (V: 49.18%) (N:  0.79%) PV: b7b6 
d8c7 ->       0 (V: 49.18%) (N:  0.75%) PV: d8c7 
f6g8 ->       0 (V: 49.18%) (N:  0.73%) PV: f6g8 
c6b4 ->       0 (V: 49.18%) (N:  0.67%) PV: c6b4 
c6d4 ->       0 (V: 49.18%) (N:  0.66%) PV: c6d4 
d8a5 ->       0 (V: 49.18%) (N:  0.54%) PV: d8a5 
c6a5 ->       0 (V: 49.18%) (N:  0.52%) PV: c6a5 
g7g5 ->       0 (V: 49.18%) (N:  0.44%) PV: g7g5 
c6b8 ->       0 (V: 49.18%) (N:  0.39%) PV: c6b8 
d8b6 ->       0 (V: 49.18%) (N:  0.34%) PV: d8b6 
h8g8 ->       0 (V: 49.18%) (N:  0.31%) PV: h8g8 
f6h5 ->       0 (V: 49.18%) (N:  0.30%) PV: f6h5 
b7b5 ->       0 (V: 49.18%) (N:  0.18%) PV: b7b5 
f6e4 ->       0 (V: 49.18%) (N:  0.12%) PV: f6e4 
f6d5 ->       0 (V: 49.18%) (N:  0.10%) PV: f6d5 
c6e5 ->       0 (V: 49.18%) (N:  0.07%) PV: c6e5 

info depth 9 nodes 10 nps 76 score cp 2 winrate 50.75% time 117 pv g7g6 g2g3 f8g7 f1g2
bestmove g7g6

and v0.5:
./lczero --threads=1 --visits=10 --weights=id106 --seed=1
Using 1 thread(s).
RNG seed from cli: 1
Detecting residual layers...v1...64 channels...6 blocks.
BLAS Core: Nehalem
position fen r1bqkbnr/pp1ppppp/2n5/2p5/P1P5/8/1P1PPPPP/RNBQKBNR w KQkq - 0 1 moves d2d3 g8f6 g1f3
go
update_root, 0 -> 0 expanded nodes (0.0% reused)
NNCache: 0/0 hits/lookups = 0.0% hitrate, 0 inserts, 0 size
info depth 6 nodes 2 nps 20 score cp 3 winrate 50.97% time 50 pv e5 Nc3
info depth 7 nodes 3 nps 27 score cp 2 winrate 50.77% time 73 pv e5 Nc3 Be7
info depth 8 nodes 4 nps 34 score cp 2 winrate 50.76% time 86 pv e5 Nc3 Be7 g3
info depth 9 nodes 7 nps 53 score cp 5 winrate 51.39% time 113 pv g6 g3 Bg7 Bg2

info string   Ne5 ->       0   (V: 49.18%) (N:  0.07%) PV: Ne5 
info string   Nd5 ->       0   (V: 49.18%) (N:  0.10%) PV: Nd5 
info string   Ne4 ->       0   (V: 49.18%) (N:  0.12%) PV: Ne4 
info string    b5 ->       0   (V: 49.18%) (N:  0.18%) PV: b5 
info string   Nh5 ->       0   (V: 49.18%) (N:  0.30%) PV: Nh5 
info string   Rg8 ->       0   (V: 49.18%) (N:  0.31%) PV: Rg8 
info string   Qb6 ->       0   (V: 49.18%) (N:  0.34%) PV: Qb6 
info string   Nb8 ->       0   (V: 49.18%) (N:  0.39%) PV: Nb8 
info string    g5 ->       0   (V: 49.18%) (N:  0.44%) PV: g5 
info string   Na5 ->       0   (V: 49.18%) (N:  0.52%) PV: Na5 
info string  Qa5+ ->       0   (V: 49.18%) (N:  0.54%) PV: Qa5+ 
info string   Nd4 ->       0   (V: 49.18%) (N:  0.66%) PV: Nd4 
info string   Nb4 ->       0   (V: 49.18%) (N:  0.67%) PV: Nb4 
info string   Ng8 ->       0   (V: 49.18%) (N:  0.73%) PV: Ng8 
info string   Qc7 ->       0   (V: 49.18%) (N:  0.75%) PV: Qc7 
info string    b6 ->       0   (V: 49.18%) (N:  0.79%) PV: b6 
info string   Ng4 ->       0   (V: 49.18%) (N:  0.79%) PV: Ng4 
info string   Rb8 ->       0   (V: 49.18%) (N:  1.03%) PV: Rb8 
info string    h5 ->       0   (V: 49.18%) (N:  1.11%) PV: h5 
info string    a5 ->       0   (V: 49.18%) (N:  1.81%) PV: a5 
info string    a6 ->       0   (V: 49.18%) (N:  2.46%) PV: a6 
info string    d6 ->       0   (V: 49.18%) (N:  3.95%) PV: d6 
info string    h6 ->       0   (V: 49.18%) (N:  5.00%) PV: h6 
info string    e6 ->       0   (V: 49.18%) (N: 14.23%) PV: e6 
info string    d5 ->       2   (V: 49.25%) (N: 15.00%) PV: d5 cxd5 Nxd5
info string    g6 ->       3   (V: 52.22%) (N: 22.44%) PV: g6 g3 Bg7 Bg2
info string    e5 ->       4   (V: 51.50%) (N: 25.29%) PV: e5 Nc3 Be7 g3 d5

info depth 9 nodes 10 nps 64 score cp 3 winrate 51.04% time 139 pv e5 Nc3 Be7 g3 d5
bestmove e7e5

**Comment by Tilps** [comment]
#292 In case we don't want to keep it.

I think using dynamic_eval instead of the static eval probably (on average... or something) has the opposite effect of fpu_reduction does, which would probably make it undesirable?

**Comment by killerducky** [comment]
This is fixed. It's an open question exactly how we want to handle FPU, but for now let's not rock the boat and keep it the same as v4.
