### ISSUE TITLE
Transposition table and learning

### ISSUE THREAD

**Issue by will-iam** [glinscott/leela-chess#29]
The transposition tables keep no record of the "repeatability state" of the position, nor history. It's very unlikely that two transposed nodes, with different history, will receive the same evaluation by the network. So returning the value of another node introduces a little inconsistency.
For instance, assume A and B, two nodes that transposes. We want to evaluate the root, if we take the path that evaluates A first, we will have a different result that if we take the path that evaluates B first.
Other example, maybe worst, A and B transposes and and just after B, the position could repeat and draws. B evaluation should be closer to 0.5 than A.
I believe this is very small and it worth to use transposition tables during play but I suggest to remove it during self-play because I fear that this little inconsistency could perturb the learning process.

**Comment by glinscott** [comment]
Currently, the ttable clears any positions that have been played in the actual game when there is a repetition.  I think this is probably enough to allow the ttable to be used during training (although I'm not 100% sure).
