### ISSUE TITLE
Please upgrade to 10B immediately.

### ISSUE THREAD

**Issue by tanguocn** [glinscott/leela-chess#298]
Training is limited to stagnation, and is urgently needed to upgrade to 10B immediately.

**Comment by jkiliani** [comment]
They can't upgrade immediately, for the reason that the new 10 block net will only work with bug-fixed 0.5 clients. The upgrade has to be enforced (which must be coordinated among devs), or some clients will be producing bad data after 10B is promoted. So the immediate upgrade is not going to happen, the upgrade will come when the code is sufficiently tested and the project developers decide on a good way to make this (complicated) process go as smoothly as possible.
