### ISSUE TITLE
Various comments

### ISSUE THREAD

**Issue by Error323** [glinscott/leela-chess#3]
Hi glinscott,

This seems interesting, I was working on my own version using caffe, also well aware of leela-zero, but maybe it's better to work together. Anyway I have two questions:

1. Why do you keep a history in the input planes? It seems to me that this is not necessary for chess. Given that the full state is observable in _s_ we'd only need 21 input planes.
2. How are you getting to a policy vector size of 1924? The paper uses a policy vector of 8x8x73 = 4672. Or more specifically 8*8 * ({1,...,7}x{N,NE,E,SE,S,SW,W,NW} + {n0,n1,...,n7} + {KNIGHT,BISHOP,ROOK}x{NW,N,NE})

Kind regards,
Error323

**Comment by Error323** [comment]
Awesome! I'll dig in. 

1. I believe it was only to show that the method and network were generic enough to support multiple games. I think using just the 21 planes already gives the full state, including draw detection (repetition planes and no-progress count plane).

2. Thank you!

For my own version I was generating a dataset from human games with elos > 2000. I think it makes sense to try and figure out if a more compact version of the network exists. As stated in 1, the network was made to serve multiple games. If we can reduce it, we save computation and we'll need all the compute we can get.

**Comment by brianprichardson** [comment]
Got it working, thanks @vondele, although @Error323's fix seems to work also.

Can create data, train, and evaluate with cutechess-cli (perhaps sprt should be used).

@glinscott Given hardware handicap v A0 (even with full distributed support ala Fishtest), does it interest you to use a more chess-specific NN, perhaps something like Giraffe's, augmented with some CNN?

Regardless, happy to contribute GTX 1070 time

**Comment by brianprichardson** [comment]
FWIW, using leelaz-model-6000.txt weights

Finished game 100 (lc_base vs lc_new): 0-1 {Black mates}
Score of lc_new vs lc_base: 36 - 6 - 58  [0.650] 100
Elo difference: 107.54 +/- 43.21

**Comment by glinscott** [comment]
@brianprichardson very cool!  Which sha is this based on?

**Comment by brianprichardson** [comment]
sha?

**Comment by brianprichardson** [comment]
in parse.py in def run_test suggest:

    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    with tf.Session(config=config) as sess:

As without this the test session consumes all GPU memory and then the per_process_gpu_memory_fraction in tfprocess.py does not seem to do much.

For my system, it only uses about 18% with a few other things running.

**Comment by glinscott** [comment]
The sha is the commit that you built.  You can get it from the first line of `git log`

**Comment by brianprichardson** [comment]
Is this it:

0000000000000000000000000000000000000000 5bf7bb81f39f6b57eeb6ba0e5ad86d0372c34761 Brian Richardson <brian@Tinker2Ubuntu.(none)> 1515783674 -0500	clone: from https://github.com/glinscott/leela-chess.git

**Comment by glinscott** [comment]
@brianprichardson yes, the 5bf7bb8 part is the sha.  So it looks like you were running the latest, which is great!
