### ISSUE TITLE
4 mate-in-one opportunities missed in one game

### ISSUE THREAD

**Issue by djinnome** [glinscott/leela-chess#306]
Similar to https://github.com/glinscott/leela-chess/issues/105  It appears that leela is missing several mate-in-one's.  I originally posted this on the [leela-chess google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!starred/lczero/NDv4xtE3W7k)

 I played through http://lczero.org/game/3873645 and realized it missed several mate-in-one opportunities, starting at **29. ... Bxf1?** instead of 29. ... Nh3++ 

![screen shot 2018-04-12 at 4 21 28 pm](https://user-images.githubusercontent.com/144210/38708999-aedfa8e2-3e6d-11e8-93da-2e5d399fd068.png)

It then played **30. ... Qxf2?** instead of 30. ... Qg2++.  
![screen shot 2018-04-12 at 4 23 24 pm](https://user-images.githubusercontent.com/144210/38709059-e6d86f04-3e6d-11e8-93a3-f6c211df832a.png)

It then played **31. ... Qg2+?** instead of 31.  ... Bg2++ or 31. ... Qg1++.  
![screen shot 2018-04-12 at 4 24 14 pm](https://user-images.githubusercontent.com/144210/38709081-fc72edf8-3e6d-11e8-8702-b146a30b040d.png)

Finally, it did play the correct move **32. ... Bxg2++**, but only after missing 4 mate-in-1 opportunities!
![screen shot 2018-04-12 at 4 24 55 pm](https://user-images.githubusercontent.com/144210/38709119-1a3588fa-3e6e-11e8-9455-c5973d18ee62.png)

I am running in CPU mode on a mac with the latest version 5 client_mac. Not sure which weights were used for this game. How would I find that out?

**Comment by Uriopass** [comment]
Training games uses T=1, which mean moves picked are not the best move but proportional to how good they seem. With 800 playouts only sometimes the network won't see mates-in-one and the time it takes for exploration to kick in is longer. This is absolutely normal and should happen less and less as time goes on.

**Comment by Dorus** [comment]
> Training games uses T=1, which mean moves picked are not the best move but proportional to how good they seem. With 800 playouts only sometimes the network won't see mates-in-one and the time it takes for exploration to kick in is longer. This is absolutely normal and should happen less and less as time goes on.

So the real question is: Does it find those 4 mate moves with 800 playouts if you load the engine and turn off randomness? If not in 800 moves how many does it need?

If it needs more than 800, it will also be interesting to do the same analyses with later networks. You'll see the nr of required playouts go down over time. Or, if it doesn't go down, something indeed is wrong.

**Comment by Dorus** [comment]
I did an analyse:

Move 25: Qg6xg3 (mate in 4) found in 35 playouts.
Move 26: Rx8xe8 (mate in 3) found in 5 playouts.
Move 27: Re8-e1 (mate in 2) found in 433 playouts. Self play did Nf4  here instead.
Move 28: Bh3xg2 (mate in 3)  found in 1k playouts.
Move 29: Nf4-h3+ (mate in 1) not found in 25000 playouts. But the mate in 1 move was the second choice with 31% playouts. Self play did Bxf1+ here instead (53% of my 24k analyses wend into this move).
Move 30: Qg3-g2+ (mate in 1) found in 6 playouts. Self play did Qxf2 here instead (5% playouts on this move in my 18k node analysis)
Move 31: Qf2-g1+ (mate in 1) found in 4 playouts. Self play did Qg2+ instead (15% playouts on this move in my 21k node analysis)
Move 21: Bf1g2+ (mate in 1) found in 4 playouts.

**Comment by Dorus** [comment]
I did it again for ID 129:

Move 25: Qg6xg3 (mate in 4) found in 5 playouts.
Move 26: Rx8xe8 (mate in 3) found in 2 playouts.
Move 27: Re8-e1 (mate in 2) found in 11k playouts. Self play did Nf4 here instead, ID 129 also has a strong preference for Nf4 here.
Move 28: Bh3xg2 (mate in 3) found in 261 playouts.
Move 29: Nf4-h3+ (mate in 1) not found in 26500 playouts. Mate in one was second choice with 36% playouts. 5% better than last time. Self play did Bxf1+ here.
Move 30: Qg3-g2+ (mate in 1) found in 2 playouts. Self play did Qxf2 here instead.
Move 31: Qf2-g1+ (mate in 1) found in 3 playouts. Self play did Qg2+ instead..
Move 32: Bf1g2+ (mate in 1) found in 3 playouts.


Move nr | Id 124 |  Id 129
-- | -- | --
25 | 35 | 5
26 | 5 | 2
27 | 433 | 11000
28 | 1000 | 261
29 | 31% | 36%
30 | 6 | 2
31 | 4 | 3
32 | 4 | 3
