### ISSUE TITLE
v 0.6 Gzip Invalid Headers

### ISSUE THREAD

**Issue by MrMonotone** [glinscott/leela-chess#321]
On Windows, after running the client, the executable exits with this output.

```
Downloading network...
Downloading network...
2018/04/14 23:15:13 gzip: invalid header
```

**Comment by glinscott** [comment]
Apologies, this was an error when moving the network storage to s3.  It's fixed now, but you need to delete your networks folder.

**Comment by MrMonotone** [comment]
Great. Its fixed now thanks!
