### ISSUE TITLE
crashes when running the v0.6 client (gpu)

### ISSUE THREAD

**Issue by andreashedman** [glinscott/leela-chess#325]
I'm running two instances, 1080ti,  i7 i980x, 12gb ram, win 7 (same folder for both clients)

The client sometime crashes when the game is completed

most recent crash and log(with -debug option)

END
Score: 1
Writing chunk 0
2018/04/15 16:25:19 Completed 7 games in 8m0.6004888s time
Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-4452/20180415162519.log --start=train 4452-7 1]
200
map[Date:[Sun, 15 Apr 2018 14:25:20 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[65] Connection:[keep-alive] Server:[nginx/1.10.3 (Ubuntu)]]
File training.0.gz uploaded successfully with fields user=hedman.
Cleanup training files:
C:\work\leelachess\data-4452-6/training.0.gz
Logging to C:\work\leelachess/logs-4452/20180415162519.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 90.
2018/04/15 16:25:26 exit status 1

earlier crash had different exit status
"2018/04/15 16:13:14 exit status 3221225477"

**Comment by andreashedman** [comment]
going to try using different folders, incase it's a concurrency releated issue

**Comment by andreashedman** [comment]
had it running for ~20-25 minutes in separate folders, no crashes/exits.
i'll see if i can reproduce the exits when running in the same folder. hopefully get some more log outputs

**Comment by andreashedman** [comment]
this error from when i ran the client in a separate folder

info depth 13 nodes 68 nps 1389 score cp -12 winrate 47.59% time 17 pv c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nxc6 bxc6 e5
info depth 14 nodes 119 nps 1310 score cp -10 winrate 48.01% time 57 pv e6 Nf3 d5 d4 Nf6 Bd3 dxe4 Nxe4 Nxe4
info depth 15 nodes 214 nps 1248 score cp -9 winrate 48.06% time 136 pv c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nxc6 bxc6 e5 Nd5
info depth 16 nodes 382 nps 1219 score cp -9 winrate 48.05% time 277 pv c5 Nf3 Nc6 d4 cxd4 Nxd4 d6 Be3 Nf6 Be2 e5 Nxc6
2018/04/15 18:08:03 exit status 3221225477

**Comment by andreashedman** [comment]
errors when running from same folder (both client exited)

END
Score: -1
Writing chunk 0
2018/04/15 18:07:00 Completed 25 games in 29m43.4070051s time
Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-7708/20180415180700.log --start=train 7708-25 1]
200
map[Date:[Sun, 15 Apr 2018 16:07:02 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[65] Connection:[keep-alive] Server:[nginx/1.10.3 (Ubuntu)]]
File training.0.gz uploaded successfully with fields user=hedman.
Cleanup training files:
C:\work\leelachess\data-7708-24/training.0.gz
Logging to C:\work\leelachess/logs-7708/20180415180700.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 90.
2018/04/15 18:07:09 exit status 1






-----------



END
Score: -1
Writing chunk 0
2018/04/15 18:07:42 Completed 60 games in 1h17m19.9003871s time
Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-11356/20180415180742.log --start=train 11356-60 1]
200
map[Content-Type:[text/plain; charset=utf-8] Content-Length:[65] Connection:[keep-alive] Server:[nginx/1.10.3 (Ubuntu)] Date:[Sun, 15 Apr 2018 16:07:43 GMT]]
File training.0.gz uploaded successfully with fields user=hedman.
Cleanup training files:
C:\work\leelachess\data-11356-59/training.0.gz
Logging to C:\work\leelachess/logs-11356/20180415180742.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 90.
2018/04/15 18:07:50 exit status 1

**Comment by andreashedman** [comment]
END
Score: -1
Writing chunk 0
2018/04/15 18:16:58 Completed 5 games in 5m59.4055568s time
Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-11776/20180415181658.log --start=train 11776-5 1]
200
map[Server:[nginx/1.10.3 (Ubuntu)] Date:[Sun, 15 Apr 2018 16:17:00 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[65] Connection:[keep-alive]]
File training.0.gz uploaded successfully with fields user=hedman.
Cleanup training files:
C:\work\leelachess\data-11776-4/training.0.gz
Logging to C:\work\leelachess/logs-11776/20180415181658.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 90.
2018/04/15 18:17:07 exit status 1


-- when restarting the client

Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-11912/20180415181849.log --start=train 11912-0 1]
Logging to C:\work\leelachess/logs-11912/20180415181849.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 90.
2018/04/15 18:18:58 exit status 1


--- after deleted the network and client redownloaded it

Downloading network...
2018/04/15 18:20:21 open networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66: The system cannot find the path specified.
2018/04/15 18:20:21 Sleeping for 30 seconds...
Downloading network...
Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-1984/20180415182108.log --start=train 1984-1 1]
Logging to C:\work\leelachess/logs-1984/20180415182108.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 90.
2018/04/15 18:21:14 exit status 1

-- 

it worked when i copied the network file from my other folder
i have a copy of the network file that kept giving me "line 90" errors

**Comment by andreashedman** [comment]
more crashes

END
Score: -1
Writing chunk 0
2018/04/15 18:27:15 Completed 3 games in 3m11.9709802s time
Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-11308/20180415182715.log --start=train 11308-3 1]
200
map[Date:[Sun, 15 Apr 2018 16:27:16 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[65] Connection:[keep-alive] Server:[nginx/1.10.3 (Ubuntu)]]
File training.0.gz uploaded successfully with fields user=hedman.
Cleanup training files:
C:\work\leelachess\data-11308-2/training.0.gz
Logging to C:\work\leelachess/logs-11308/20180415182715.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 90.
2018/04/15 18:27:24 exit status 1

C:\work\leelachess>start .

C:\work\leelachess>client.exe -debug
Downloading network...
2018/04/15 18:30:38 open networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66: The system cannot find the path specified.
2018/04/15 18:30:38 Sleeping for 30 seconds...
Downloading network...
Args: [C:\work\leelachess/lczero --weights=networks\41300dcb6321189b5d291425ddd3a455fed7265bc0049f22238deb09a2340c66 -t1 --randomize -n -v800 -lC:\work\leelachess/logs-656/20180415183126.log --start=train 656-1 1]
Logging to C:\work\leelachess/logs-656/20180415183126.log.
Using 1 thread(s).
Detecting residual layers...v2...128 channels...10 blocks.

Failed to parse weight file. Error on line 58.
2018/04/15 18:31:30 exit status 1

C:\work\leelachess>


i copied leelachess to leelachess-3
removed all folders, (data, log, networks)
removed settings.json

after that it downloaded the network and it seem to work (a few games completed)

(i have a copy of the network file that fail on line 58)

**Comment by killerducky** [comment]
Please upload a failed network file somewhere, maybe the line 58 one.

**Comment by killerducky** [comment]
andreashedman sent me two examples. One of them there is a random "v" where there should be a "6". The other I didn't find the character but the sha256 shows the file is corrupted somehow. He is going to run a memtest, smells like a bit got flipped. 

Note "6" is 0x36 and "v" is 0x76 in ASCII so they are 1 bit off.
