### ISSUE TITLE
Other backends for Lc0-tf

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#332]
Currently lc0 only supports CUDA/cuDNN tensorflow backend.
That makes it hard to compile, and not useful for people without NVidia GPU.

Therefore, the plan is to port from lczero.exe or implement:

- openCL backend
- CPU backend
- Tensorflow CPU (requires transposition of input data, tensorflow-CPU doesn't support NCHW convlayer)

**Comment by Error323** [comment]
Is there anyone with OpenCL knowledge willing to write a backend for this? @gcp or @Ttl can we convince you guys to look into it? :)

**Comment by gcp** [comment]
I think Network.cpp/OpenCL.cpp/OpenCLScheduler.cpp/Tuner.cpp should be fairly well portable to another program, just have to get rid of some myprintf and remove the reliance on the LZ threadpool in OpenCLScheduler (which you can find in the original pull request, as it was using std::async originally). Most of the other stuff is C++ with low dependencies and with the occasional boost helper function.

That will give you both OpenCL and CPU support. CPU support should be reasonable though probably not 100% competitive with say MKL-DNN as the Winograd part of the code isn't vectorized.

As for porting this into /lc0, it's not terribly motivating for me to do that when I can't port improvements to the engine back and forth, unlike with the original leela-chess. I'd rather add batching to that...

**Comment by Error323** [comment]
>I think Network.cpp/OpenCL.cpp/OpenCLScheduler.cpp/Tuner.cpp should be fairly well portable to another program, just have to get rid of some myprintf and remove the reliance on the LZ threadpool in OpenCLScheduler (which you can find in the original pull request, as it was using std::async originally). Most of the other stuff is C++ with low dependencies and with the occasional boost helper function.

Yeah this is probably what we'll be doing although it's still a non trivial operation for people with no OpenCL knowledge.

>As for porting this into /lc0, it's not terribly motivating for me to do that when I can't port improvements to the engine back and forth, unlike with the original leela-chess. I'd rather add batching to that...

I understand. However, maybe you want to consider adopting this version also? It'll give a huge boost to leela-zero.
I understand

**Comment by Error323** [comment]
Note that we've been given permission by NVIDIA to distribute cudnn with our binaries.

**Comment by gcp** [comment]
>maybe you want to consider adopting this version also. It'll give a huge boost to leela-zero.

I've considered it but my conclusion was that I'd rather add (back) batching.

>Note that we've been given permission by NVIDIA to distribute cudnn with our binaries.

Perhaps @mooskagh could consider adding a linking exception to the GPL for lc0. Right now I wouldn't be entirely sure whether anyone else can actually distribute a binary with cuDNN support, as it involves linking a GPL program with proprietary code. As long as @mooskagh writes all the code (and publishes the binaries) it literally doesn't matter because he is the copyright owner and can do whatever he wants, but if he pulls in contributions to lc0 it becomes an issue.

The alternative is to re-license under MIT or BSD or whatever, but then you risk closed source clones, which you may or may not care about.

**Comment by Domaldel** [comment]
May I suggest using hipDNN?
It's very similar to cuDNN except for also having support for AMDs alternatives.
(MIOpen etc)
