### ISSUE TITLE
Linux executable not found

### ISSUE THREAD

**Issue by jmaister** [glinscott/leela-chess#346]
I downloaded `client_linux` from https://github.com/glinscott/leela-chess/releases however, the executable `lzcero` is not available:
```

jordi@patricio:~/projects/lczero$ ./client_linux
Args: [/home/jordi/projects/lczero/lczero --weights=networks/5874188a811510e7b5867282296c8fc75ba4eb12b4eabcc42a3000aca7bfdc3d -t1 --randomize -n -v800 --start=train 19932-0 1 --quiet]
2018/04/17 22:02:58 fork/exec /home/jordi/projects/lczero/lczero: no such file or directory
```

**Comment by jjoshua2** [comment]
You have to build it. According to the readme https://github.com/glinscott/leela-chess

**Comment by jmaister** [comment]
I understand it now. It is not clear that the linux version requires to build it.
As I started using the Windows version that already provides the executable.

Could an executable for linux be added ?
