### ISSUE TITLE
Games drawn too early in match games

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#350]
Comes from library claiming draws after 25 moves instead of 50: https://github.com/notnil/chess/issues/16

**Comment by smk-kent** [comment]
This may be slightly more serious. Consider this match game: http://lczero.org/match_game/100223
This was drawn by (problematic) the 25-move-rule. However, the final position is check-mate. So, this should be a win regardless, and also correspondingly under the 50-move rule, so I suspect the rules are not correctly implemented.

**Comment by killerducky** [comment]
I saw in my email someone pointed out a related bug, but when I clicked to the github site the comment is not here, very strange. Well here is the issue they found:

> Consider this match game: http://lczero.org/match_game/100223
> This was drawn by (problematic) the 25-move-rule. However, the final position is check-mate. So, this should be a win regardless, and also correspondingly under the 50-move rule, so I suspect the rules are not correctly implemented.

The game is listed here as a draw: http://lczero.org/match/142

**Comment by killerducky** [comment]
Now I see @smk-kent created #363 but closed it?

**Comment by Tilps** [comment]
yeah it was mistakenly identified checkmate.

**Comment by killerducky** [comment]
Uh.... yeah   :)  haha  I will be brave and leave my comments to be judged as they are, guess I'll strike them so other people don't panic though. ;-)

**Comment by killerducky** [comment]
Fixed in v0.8
