### ISSUE TITLE
Port tree re-use over from Leela Zero

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#37]
https://github.com/gcp/leela-zero/commit/081bd715bdc2a8ab035f992253e8efd3597338ec

**Comment by killerducky** [comment]
Hey I just found this repo, just a quick note to say good luck! Looking forward to seeing some results for leela-chess.

**Comment by Error323** [comment]
How much of a boost will this give @killerducky ?

**Comment by jkiliani** [comment]
Currently, we have the transposition table and NN cache active for lczero, but no tree reuse?

**Comment by Error323** [comment]
I ripped out TTable, NNCache is still todo and so is tree reuse I think, but I'm not sure...

**Comment by killerducky** [comment]
For tree reuse, LZGo self play games average 68% reused. It will be less for a new network. Also since chess uses temperature=1 the entire game, that will lower the amount of reuse.

For NNCache, LZGo has around 12% hit rate.

**Comment by killerducky** [comment]
See #107 and #26.

There is a problem with tree reuse and Dirichlet noise. Suppose we reuse 790 visits from the previous tree. We add Dirichlet noise, but now there are only 10 visits left that use the noised values. I think it might be better to not do tree-reuse for self play games.

NNCache can handle most of this anyways, especially for small visit counts like we have now. Full tree reuse could be more helpful in cases where we are thinking/pondering for a very long time and NNCache overflows.

Here is my WIP branch on this:
https://github.com/killerducky/leela-chess/tree/treereuse
