### ISSUE TITLE
Possible bug with late En passant

### ISSUE THREAD

**Issue by shellster** [glinscott/leela-chess#370]
I posted this in the dev Discord, and no one seemed to be able to quickly point out an error in my analysis.  It would come up rarely, so it might go unnoticed.  I don't know that this is a problem, but I'm adding an issue so someone more knowledgeable than me can take a look at some point:

I think I may have spotted a bug in the source, but I'm not sure.  https://github.com/glinscott/leela-chess/blob/61cd0938ba176b0b27d787cd9a62ce6c81c2ed9a/lc0/src/chess/board.cc#L312

Does this En passant code know that it can only happen immediately after the pawn jumps two squares.  I very likely am not reading this code correctly, but I don't see any protection to prevent Leela from trying to capture En passant a move later.

Someone mentioned that move generation came from Stockfish, but the code in Stockfish looks significantly different, way more conditions and all moves are not lumped into one conditional, so it is likely that checks were missed: https://github.com/official-stockfish/Stockfish/blob/e9aeaad05266ca557a9496b5a17b4c5f82f0e946/src/movegen.cpp#L207

**Comment by killerducky** [comment]
You linked to the WIP tensorflow implementation that @mooskagh is working on, it is not used right now. See src/Movegen.h for the code we're actually using right now.

I quickly looked at the code, I don't know how it works. Maybe pawns_ is the state of pawns in the previous move, and 7 means the pawn used to be on 7th, and the 5 means it is now on the 5th? Just a total guess.

**Comment by mooskagh** [comment]
pawns_ plane uses rows 0 and 7 to encode en passant possibility. It is checked in that line, and those rows are actually cleared [here](https://github.com/glinscott/leela-chess/blob/61cd0938ba176b0b27d787cd9a62ce6c81c2ed9a/lc0/src/chess/board.cc#L364) when the move is applied.

Sorry that it's not obvious from the code, I will add comments.
It's also possible that I will switch from this movegen into stockfish movegen.

**Comment by shellster** [comment]
Thanks for the explanation!
