### ISSUE TITLE
Improve UCI support

### ISSUE THREAD

**Issue by Error323** [glinscott/leela-chess#39]
http://wbec-ridderkerk.nl/html/UCIProtocol.html

**Comment by alwey** [comment]
reference got hacked

**Comment by Error323** [comment]
@glinscott what is a good reference site for the UCI protocol?

**Comment by Ipmanchess** [comment]
@Error323 ..here you go : http://wbec-ridderkerk.nl/html/UCIProtocol.html

**Comment by Error323** [comment]
That's the one I referred to at the start of this issue indeed. But it's hacked? @alwey what do you mean?

**Comment by alwey** [comment]
@Ipmanchess:
This is a compromised page, unless there has been an update in the specifications like:

Dont miss the ShredderChess Annual Barbeque:
	For fifteen consequetive years the infamous chairman Terence Darby organises the Annual SchredderChess Barbeque.
	This event is co organised by the Dutch official big green eggfanwebsite on a vast barbeque the big green XXl.
	This XXlarge barbeque proved to be perfect for hosting a party of fifty people throughout the day.
	"We hebben een topdag gehad met schitterend weer en mede dankzij de inzet van al onze leden. We hebben eens niet
	tegen een computer geschaakt maar lekker face 2 face tegen elkaar."
	The Annual barbeque is hosted by www.shredderchess.com and is held every year on the 7th of august. See you in 2018!

**Comment by Error323** [comment]
I thought it was kind of a joke. shredderchess builders designed the protocol right?

**Comment by alwey** [comment]
Use the wayback archive to compare versions.

**Comment by Ipmanchess** [comment]
I think it's just a forgotten part off the site..will check again..

**Comment by alwey** [comment]
This is an old page and I think I saved the spec some years ago. I liked the format. The official version of the spec is uvailable at shredderchess.com
http://download.shredderchess.com/div/uci.zip .

**Comment by Ipmanchess** [comment]
Thanks..is the same..updated 2006

**Comment by alwey** [comment]
Nah, at shredderchess.com they omitted the barbecue part of the specification ;-).

**Comment by glinscott** [comment]
Time control in, and it's being played in GUIs now, so I think good enough for a start :).
