### ISSUE TITLE
Compile on Windows?

### ISSUE THREAD

**Issue by Akababa** [glinscott/leela-chess#42]
Has anyone been able to get this working on Windows? I spent all day trying to compile it in MSYS2 but to no avail.

**Comment by glinscott** [comment]
@Akababa are you able to compile leela-zero on windows?

**Comment by glinscott** [comment]
Windows builds are now automatically created by Appveyor!  https://groups.google.com/forum/#!topic/lczero/bFOIt90mlD8

**Comment by Ipmanchess** [comment]
I have download lczero compile.. start it and get first that i'm missing OpenCL.dll ..download it ,put in same folder ,then start lczero and get this error now: 

https://mega.nz/#!LNwHnBLL!pNfRfaVWBVwzjcZA0RxycBRZenfs5OCVNCyC1V_ZHSQ
