### ISSUE TITLE
--noponder and -p options not working in version 0.7 (Windows cpu lczero.exe)

### ISSUE THREAD

**Issue by kvnkrkptrck** [glinscott/leela-chess#444]
I'm running Leela as Arena 3.5.1 engine on Windows 10 machine.  I am trying to limit playouts to a fixed number using -p option.  The documentation (both at this link: https://github.com/glinscott/leela-chess/wiki/Running-Leela-Chess-Zero-in-a-Chess-GUI and in the -h output) indicates that --noponder is required.  Sure enough, if I use -p option alone, engine log gives error:

2018-04-26 12:28:45.284<--1:Nonsensical options: Playouts are restricted but thinking on the opponent's time is still allowed. Add --noponder if you want a weakened engine.

However, it also seems the --noponder option is no longer recognized.  When both -p and --noponder option are used (or just --noponder alone), the engine log gives error:
2018-04-26 12:22:39.151<--1:ERROR: unrecognised option '--noprompt'

These are contradictory, which makes the -p option completely unusable.

**Comment by kvnkrkptrck** [comment]
Okay, it seems this was an Arena issue, not a Leela issue.   My suspicion is that Arena 3.5.1 on Windows is doing some kind of caching whereby swapping in a new binary does not completely flush the old binary 
 
In case such a symptom is reported down the road, I recommend the following steps to resolve the issue:
1) Delete Arena entry for existing lczero.exe engine.
2) Delete folder containing lczero binaries.
3) Close Arena
3) Re-download and unzip latest/greatest version of lczero binaries (preferably, if possible, into a novel folder name)
4) Open Arena.
5) Add fresh download as a new engine in Arena (preferably, if possible, using a differently-named engine) according to instructions on Leela wiki page.

After performing the above steps myself, the issue was resolved and I have bee completely unable to replicate.

**Comment by mooskagh** [comment]
Noponder is indeed removed from "next" branch, so in v0.8 it won't work.
lczero doesn't ponder anyway.
