### ISSUE TITLE
Conform to UCI Standard

### ISSUE THREAD

**Issue by heronils** [glinscott/leela-chess#468]
It is desirable that Leela conforms to the [UCI protocol standard](http://wbec-ridderkerk.nl/html/UCIProtocol.html):

Currently Leela sends info strings which look like this:

`info depth 16 nodes 593 nps 56 score cp 6 winrate 51.23% time 10582 pv e4 c5 c3 e6 d4 a6 dxc5 Bxc5 Bd3 Nc6 Nd2 Qg5`

Here there are two things to note:

1) Leela does not encode moves in long algebraic notation (the part after `pv`) which is against the standard, Quote:

    > Move format:
    > ------------
    > 
    > The move format is in long algebraic notation.
    > A nullmove from the Engine to the GUI should be send as 0000.
    > Examples:  e2e4, e7e5, e1g1 (white short castling), e7e8q (for promotion)
    
    That should be the reason why for example Scid shows no output. Other GUIs are more forgiving, Scid is strict here.

2) Leela sends `winrate 51.23%` which his is also mentioned nowhere in the standard (see _engine to gui_ -> _info_), but also according to the standard GUIs should handle that (and Scid probably does once the move format fits):

    > * if the engine or the GUI receives an unknown command or token it should just ignore it and try to parse the rest of the string.
    
3) Further, Leela needs a while on every position change until it sends an info line - which is not against the standard, it just makes it unusable for analysis - and it also always stops on a specific depth, which is against the standard. The standard defines `go infinite` as:

    > * (go) infinite
    > 		search until the "stop" command. Do not exit the search without being told so in this mode!
    > 

---

Please see also here:
https://groups.google.com/forum/#!msg/lczero/XVsbP_CmgLk/AJTo5bMOBAAJ

**Comment by renouve** [comment]
May be related to [https://github.com/glinscott/leela-chess/commit/e2deb04118b76888fb03b5c8036ab56910b99da2](url)

**Comment by heronils** [comment]
@renouve you can just write #340 ;-)

**Comment by renouve** [comment]
ok, thanks :)

**Comment by killerducky** [comment]
@heronils what build are you using? It seems you are using some intermediate build because v0.7, current master, and current next do not output "winrate".

The other issues are also fixed in latest next and will be included in v0.8.

**Comment by heronils** [comment]
Hmm, this is weird, i use the CPU version downloaded from here:

https://github.com/glinscott/leela-chess/releases

I was pretty sure i used v 0.7. I have now downloaded this again (version 7.0) and now Scid shows the correct output. Also it doesnt stop pondering any more and it also immediately shows the ponder lines - seems everything is fixed, thanks a lot. Can be closed.
