### ISSUE TITLE
Wiki Issue -- Getting Started  -- Get the latest version of client_mac: Download it 

### ISSUE THREAD

**Issue by hundalhh** [glinscott/leela-chess#479]
I don't know where to post a correction to the Wiki, so I'm posting it here.

The Wiki States "Note that you will need to download the client using another browser than Safari, or else you will get a .dms file which will not work."

I tried to download client_mac using Chrome 65.0.3325.181 (High Sierra 10.13.4).  The resulting download file has no extension.  If you add the extension .dmg, it still does not work.

**Comment by IanOsgood** [comment]
It isn't a .dmg, it is a Mach-o executable.  Just follow the instructions and do `chmod +x client_mac` to allow it to be executed.  (They really ought to distribute this in an archive, so that the execute bit is preserved.)
