### ISSUE TITLE
poor performance with old GPU

### ISSUE THREAD

**Issue by pw31** [glinscott/leela-chess#496]
On my 4 x Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz, lczero with network 227, CPU only version, 
I get a performance of about 50 nps when using 2 CPU, and about 55 nps when using 4 CPU.  This is
very similar whether I run on Linux or on Windows.

Switching to GPU support (which I can only do under Windows), dissapointingly, gives me an even poorer performance, about 45 nps. My GPU is NVIDIA  GeForce GT 525M.  Is this normal, or does that mean that it's actually not working properly?

Thanks!

**Comment by gcp** [comment]
Sounds perfectly normal, the GT 525M is more of a display electronics card, it barely has any hardware on it that can compute things.

**Comment by Akababa** [comment]
Your GPU at least has 96 CUDA cores, so I suggest you try the cudnn version: https://crem.xyz/lc0/

**Comment by pw31** [comment]
Thanks. I found this page which shows what to expect ...
https://docs.google.com/spreadsheets/d/1lGFf6PLGmBUSMan-YP7Vul4DpRNfn6K8oeCjBILe6uA/edit#gid=0
