### ISSUE TITLE
OpenCL calculation error

### ISSUE THREAD

**Issue by Error323** [glinscott/leela-chess#5]
Having played 1912 games, 607 had an error > 5% in the OpenCL calculation. The average OpenCL error was 26.5%. Do others experience this also?

`grep 'error=' training.out | cut -d' ' -f11 | cut -d'=' -f2 | cut -d'%' -f1 > errors.txt`

``` octave
>> load errors.txt
>> mean(errors)
ans =  26.452
>> std(errors)
ans =  56.250
>> min(errors)
ans =  5.0110
>> max(errors)
ans =  632.42
```

#### System configuration:
Ubuntu 16.04
Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
Platform version: OpenCL 1.2 CUDA 9.1.98
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 1080 Ti
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 387.34
Device speed:  1657 MHz
Device cores:  28 CU
Device score:  1112
Device ID:     1
Device name:   GeForce GTX 1080 Ti
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 387.34
Device speed:  1657 MHz
Device cores:  28 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 1080 Ti
with OpenCL 1.2 capability
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64

**Comment by Error323** [comment]
Using trained weights seems to resolve the issue.

**Comment by vondele** [comment]
also here quite a few errors (with the random weights).

**Comment by glinscott** [comment]
Yes, with the random weights I also see some small errors.  It implies there might be something just a little wrong with the batchnorm section (either CPU or GPU side), as the "random" weights for that section are all either 0.0, or 1.0.

**Comment by glinscott** [comment]
But using trained weights, I don't see any errors.

**Comment by brianprichardson** [comment]
My test with the gpu limits also in fact was using trained weights, IIRC

**Comment by Error323** [comment]
This still seems to be an issue, for me at least when running multiple instances. The probability of it occuring does seem fairly low though. I'd like to propose we only throw an error when it occurs over _x_ times in _t_ seconds?
