### ISSUE TITLE
Bug in use of time controls

### ISSUE THREAD

**Issue by chara1ampos** [glinscott/leela-chess#503]
I am playing Stockfish vs Leela Chess Zero on Arena. Both are setup as UCI engines and I use network #234 for Lc0. Time controls are set to fixed time per move (6 seconds).

While Stockfish uses the whole 6 seconds to think (search), Lc0 plays instantly. It does not use any of the 6 seconds to think. As a result, it does not search deeply at all, and loses very fast to Stockfish.

Is this expected behavior? I would think this is a bug in use of time controls.

**Comment by killerducky** [comment]
Dup of #448
