### ISSUE TITLE
Add major.minor.patch version support

### ISSUE THREAD

**Issue by killerducky** [glinscott/leela-chess#507]
It would be nice to be able to do v0.8.0, v0.8.1, etc. I don't think the current code supports this.

**Comment by mooskagh** [comment]
Btw I intended to write release script in #361, and still can if needed. I just need feedback that what I outlined there sounds good before I proceed.

**Comment by killerducky** [comment]
Also maybe client should enforce lock-step with lczero. I see many people running client 7 and lczero 8, and vice-versa. I think the policy is to always rev these together, even if there are no changes to one of them. When server enforces v8 this problem will go away so not urgent.

**Comment by Tilps** [comment]
Well I would imagine a world where the client is much less frequently updated than the engine, being quite reasonable.  So long as the server can enforce each version number I don't think its an issue the client should need to worry about.

**Comment by killerducky** [comment]
Fixed now.
