### ISSUE TITLE
TB: root_probe should increment m_tbhits

### ISSUE THREAD

**Issue by killerducky** [glinscott/leela-chess#517]
https://groups.google.com/forum/#!topic/lczero/7cmdEUFavN8

He doesn't say exactly what is wrong, but he loaded a KNBvK endgame, and I think he's expecting to see TB hits. If we count every legal move in the root as TB hits this will probably help a bit.

I wrote back in the google group:
> It should be working, but root_probe hits are not reported to the GUI. Only captures or pawn moves are reported. Right now it should be doing root_probe, eliminate losing/drawing moves, and then do it's own search to pick which of the several winning moves to play.

> Please test playing it out and report back if it ever fails to win this endgame.

**Comment by jjoshua2** [comment]
I think sf does that and it's expected.

**Comment by killerducky** [comment]
Can you clarify what SF does? It does what we do now or it does what I'm proposing?
