### ISSUE TITLE
OpenCL error on GPU

### ISSUE THREAD

**Issue by anhhuyalex** [glinscott/leela-chess#519]
Hello, I obtain an error message when trying to run ./client_mac -debug -gpu 1

Here's a pastebin of the error logs (removed the OpenCL numerical error messages). https://pastebin.com/6sPxL1mX 

Could you help me figure out the problem?

Much thanks,
Alex.

**Comment by ganeshkrishnan1** [comment]
Is it Intel graphics card?

**Comment by anhhuyalex** [comment]
That's right.

**Comment by ganeshkrishnan1** [comment]
tensorflow uses CUDA which means only nvidia gpus. Can you remove the gpu flag and try again?

**Comment by anhhuyalex** [comment]
Thanks. So that means I won't be able to use the Intel GPU?

**Comment by gcp** [comment]
TensorFlow doesn't even enter the picture here, and CUDA isn't required to play games at all.

However, it seems the drivers for your card are broken. Unfortunately a common occurrence on mac.
