### ISSUE TITLE
Implement benchmarks in lc0

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#527]
Implement the following benchmarks in "new" `lc0`:

- Perft (already implemented in tests)
- Running backend computation in loop without MCTS
- "nodes 130000" from starting position
- Something which evaluates precision of NN evaluation by backend, but I don't know where to get ground truth from.

**Comment by cn4750** [comment]
For a benchmark command, something that tests a variety of positions from the early, middle, and late game would be best. Ideally, something like what Stockfish uses [here](https://github.com/official-stockfish/Stockfish/blob/master/src/benchmark.cpp).

**Comment by CMCanavessi** [comment]
A nice option too would be to run the benchmark routine the 1st time it's launched and create a config file with the best parameters? Or maybe optional, similar to --tuner

**Comment by mooskagh** [comment]
This issue was moved to LeelaChessZero/lc0#15
