### ISSUE TITLE
Change readme for go client to point to lczero

### ISSUE THREAD

**Issue by jhamfler** [glinscott/leela-chess#608]
README.md for running the client doesn't contain the hostname and therefore doesn't work out of the box. Please change the readme from
https://github.com/glinscott/leela-chess/blob/8c6a66ddc14416dc48ed02e67ef2111315b53c80/go/src/client/README.md#L27

to
`./client --hostname=http://lczero.org --user=myusername --password=mypassword`

**Comment by dubslow** [comment]
Except it does work out of the box? I've never specified a hostname and it runs fine for me...

**Comment by jhamfler** [comment]
I tested it in a VM and it works for me now too. Not sure why it didn't work on my host.
