### ISSUE TITLE
README.md build example doesn't run

### ISSUE THREAD

**Issue by rajb245** [glinscott/leela-chess#61]
The README.md example for how to clone and build the project doesn't work as written. You need to tell git to pull the submodules too on the clone (GoogleTest), otherwise you get a cmake error saying the directory gtest can't be excluded because it doesn't contain a CMakeLists.txt; patch is:

```
diff --git a/README.md b/README.md
index e38d897..fb78cd4 100644
--- a/README.md
+++ b/README.md
@@ -102,7 +102,7 @@ This runs an evaluation match using cutechess-cli.
     sudo apt install clinfo && clinfo

     # Clone github repo
-    git clone git@github.com:glinscott/leela-chess.git
+    git clone --recurse-submodules git@github.com:glinscott/leela-chess.git
     cd leela-chess
     mkdir build && cd build
     cmake ..
```

**Comment by Error323** [comment]
Indeed, I forgot to update the README.md for this, thanks @rajb245.
