### ISSUE TITLE
lc0: bestmove not sent in analysis mode

### ISSUE THREAD

**Issue by evalon32** [glinscott/leela-chess#616]
When moving between positions in analysis mode, a GUI will typically send a `stop` command immediately followed by `position [...]` and `go infinite`. When this happens, `lc0` never outputs a `bestmove` from the last search (`lczero` does). UCI requires `bestmove` and some GUIs (XBoard, at least) do not work without it.

**Comment by mooskagh** [comment]
Fixed.

**Comment by evalon32** [comment]
Thanks! I can confirm analysis now works in XBoard.
