### ISSUE TITLE
lc0 fails to compile on Mac

### ISSUE THREAD

**Issue by gsobala** [glinscott/leela-chess#617]
**Currently lc0 fails to compile on Mac**

tensorflow_cc libraries can be installed from https://github.com/FloopCZ/tensorflow_cc

However even though the tensorflow_cc libraries install correctly into /usr/local/lib/tensorflow_cc as they do on Ubuntu, and test tensorflow c++ programs compile and run successfully, the meson installer for lc0 fails to find the tensorflow_cc library.

There apparently is an issue with rpath on the macos version of meson and this may be the stumbling block. https://github.com/mesonbuild/meson/issues/3077

A further issue is that clang on macos does not support <experimental/filesystem> (stdc++fs), and the user would need to compile a custom vesion of libc++. I never got this far.

**I outline below some of the steps I used to get as far as I did:**

It is possible with a bit of work to get the shared library of tensorflow_cc to install successfully.

Requirements include (at least):

Xcode must be installed
```
brew install coreutils curl git cmake unzip autoconf autogen automake libtool mlocate zlib wget
```
and you will need python3 with pip numpy and wheel

bazel is also required. Accept the Xcode licence beforehand
```
sudo xcodebuild -license accept
brew cask install java8
brew install bazel
```
(This *should* work but ultimately I used the binary download from https://docs.bazel.build/versions/master/install-os-x.html instead and installed it into /usr/local/bin)

then you need to delete the line containing "sed" from tensorflow_cc/cmake/TensorflowShared.cmake
then do 
```
git clone https://github.com/FloopCZ/tensorflow_cc.git
cd tensorflow_cc/tensorflow_cc
mkdir build && cd build
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
make && make install
```
There are issues with binaries finding the .so file which can be solved by copying libtensorflow_cc.so fro /usr/local/lib/tensorflow_cc to /usr/local/lib. Apparently this is because macos is strict about where @rpath points and may also explain meson's problems.

As I do not have an nVidia GPU I edited the meson.build file in lc0 as follows:
```
project('lc0', 'cpp', default_options : ['cpp_std=c++14'])

add_global_arguments('-Wthread-safety', language : 'cpp')
cc = meson.get_compiler('cpp')

# Installed from https://github.com/FloopCZ/tensorflow_cc
tensorflow_cc = declare_dependency(
  include_directories: include_directories(
    '/usr/local/include/tensorflow',
    '/usr/local/include/tensorflow/bazel-genfiles',
    '/usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads',
    '/usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/eigen',
    '/usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp',
    '/usr/local/include/tensorflow/tensorflow/contrib/makefile/downloads/nsync/public',
    '/usr/local/include/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/include',
  ),
  dependencies: [
      cc.find_library('libtensorflow_cc', dirs: '/usr/local/lib/tensorflow_cc/'),
      cc.find_library('dl'),
      cc.find_library('pthread'),
      cc.find_library('libprotobuf', dirs: '/usr/local/lib/tensorflow_cc/'),
  ],
)

deps = []
deps += tensorflow_cc
deps += cc.find_library('stdc++fs')
deps += cc.find_library('pthread')
#deps += cc.find_library('libcublas', dirs: ['/opt/cuda/lib64/', '/usr/local/cuda/lib64/'])
#deps += cc.find_library('libcudnn', dirs: ['/opt/cuda/lib64/', '/usr/local/cuda/lib64/'])
#deps += cc.find_library('libcudart', dirs: ['/opt/cuda/lib64/', '/usr/local/cuda/lib64/'])
# deps += cc.find_library('libprofiler', dirs: ['/usr/local/lib'])

#nvcc = find_program('nvcc')
#cuda_files = [
#  'src/neural/network_cudnn.cu',
#]

#cuda_gen = generator(nvcc,
#    output: '@BASENAME@.o',
#    arguments: ['--std=c++14', '-c', '@INPUT@', '-o', '@OUTPUT@', '-I', '../src'],
#)

files = [
  'src/analyzer/analyzer.cc',
  'src/analyzer/table.cc',
  'src/chess/bitboard.cc',
  'src/chess/board.cc',
  'src/chess/position.cc',
  'src/chess/uciloop.cc',
  'src/mcts/node.cc',
  'src/mcts/search.cc',
  'src/neural/cache.cc',
  'src/neural/encoder.cc',
  'src/neural/factory.cc',
  'src/neural/loader.cc',
  'src/neural/writer.cc',
  'src/neural/network_mux.cc',
  'src/neural/network_random.cc',
  'src/neural/network_tf.cc',
  'src/utils/commandline.cc',
  'src/utils/optionsdict.cc',
  'src/utils/optionsparser.cc',
  'src/utils/random.cc',
  'src/utils/string.cc',
  'src/utils/transpose.cc',
  'src/engine.cc',
  'src/selfplay/game.cc',
  'src/selfplay/tournament.cc',
  'src/selfplay/loop.cc',
#  cuda_gen.process(cuda_files)
]

includes = []
includes += include_directories('src')

executable('lc0', 'src/main.cc',
  files, include_directories: includes, dependencies: deps)


### Tests

#test_deps = deps
#test_deps += dependency('gtest')

#test('ChessBoard',
#  executable('chessboard_test', 'src/chess/board_test.cc',
#  files, include_directories: includes, dependencies: test_deps
#))

#test('HashCat',
#  executable('hashcat_test', 'src/utils/hashcat_test.cc',
#  files, include_directories: includes, dependencies: test_deps
#))
```

**Comment by mooskagh** [comment]
I've made some changes to meson.build.
It doesn't include features if libraries are not found, so no manual edit of meson.build should be needed. Could you check that I didn't break anything?

As for experimental/filesystem, I'll plan to fix that today.

**Comment by gsobala** [comment]
Your final solution will need to find a fix for the fact that on the mac, meson is terminally unable to find libtensorflow_cc.so even though it is in the right location and even if it is moved to /usr/local/lib

Believe I have tried all sorts of fixes in the last few hours and I cannot get round this.

This may be related to Apple's decision to deprecate DYLD_LIBRARY_PATH (unless SIP is disabled).

Is there a way of hard coding this in meson for mac rather than using cc.find_library() ?

(Interestingly the example tensorflow program in the Floopcz git only executes successfully on the mac either if libtensorflow_cc.so is moved to /usr/local/lib or if the @rpath is added to /usr/local/lib/tensorflow in the executable using install_name_tool -add_rpath )

I have quite happily compiled a tensorflow-cpu only build of lc0 in a tensorflow_cc docker container, so the problems are all very macos specific.

**Comment by so-much-meta** [comment]
That was on master... Just noticed I should probably be looking at "next"... Will try that now.

**Comment by so-much-meta** [comment]
The build worked for me on the "next" branch without any modification, and without using the clang installed from brew. Thanks!

**Comment by gsobala** [comment]
I am unsure whether you have successfully compiled lc0 in either branch.

In the master branch you appear to have disabled compilation of src/neural/network_tf.cc as well as cuda. This will leave you with a random move generator

The next branch has been updated since I last posted and the dependency on experimental/filesystem has been removed. So it does compile on macos but still fails to find tensorflow_cc:

```
Georges-iMac-Pro-2:lc0 george$ ./build.sh 
The Meson build system
Version: 0.46.0
Source dir: /Users/george/Development/leela-chess/lc0
Build dir: /Users/george/Development/leela-chess/lc0/build/release
Build type: native build
Project name: lc0
Native C++ compiler: c++ (clang 9.1.0 "Apple LLVM version 9.1.0 (clang-902.0.39.1)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library pthread found: YES
Library dl found: YES
Library libtensorflow_cc found: NO
Library libprotobuf found: YES
Library cublas found: NO
Library cudnn found: NO
Library cudart found: NO
Program /usr/local/cuda-9.2/bin/nvcc found: NO
Program /usr/local/cuda-9.1/bin/nvcc found: NO
Program nvcc found: NO
Dependency GTest found: NO
Build targets in project: 1
Found ninja-1.8.2 at /usr/local/bin/ninja
~/Development/leela-chess/lc0/build/release ~/Development/leela-chess/lc0
[28/28] Linking target lc0.
~/Development/leela-chess/lc0
Georges-iMac-Pro-2:lc0 george$ 
```

... so again this is a random mover as shown below

```
Georges-iMac-Pro-2:release george$ ./lc0 -w 305.txt 
       _
|   _ | |
|_ |_ |_| built May 19 2018
uci
id name The Lc0 chess engine.
id author The LCZero Authors.
option name Network weights file path type string default <autodiscover>
option name Number of worker threads type spin default 2 min 1 max 128
option name NNCache size type spin default 200000 min 0 max 999999999
option name NN backend to use type combo default random var random var multiplexing
option name NN backend parameters type string default 
option name Scale thinking time type string default 1.500000
option name Minibatch size for NN inference type spin default 256 min 1 max 1024
option name Max prefetch nodes, per NN call type spin default 32 min 0 max 1024
option name Cpuct MCTS option type string default 1.200000
option name Initial temperature type string default 0.000000
option name Moves with temperature decay type spin default 0 min 0 max 100
option name Add Dirichlet noise at root node type check default false
option name Display verbose move stats type check default false
option name Enable smart pruning type check default true
option name Virtual loss bug type string default 0.000000
option name First Play Urgency Reduction type string default 0.200000
option name Length of history to include in cache type spin default 7 min 0 max 7
option name Do debug logging into file type string default 
uciok
```
(see the default on the "NN backend to use" line)

**Comment by gsobala** [comment]
I have now successfully compiled the 'next' branch on macos for tensorflow-cpu but had to use the following kludges. These are necessary as ```tf_tensorflow_lib = cc.find_library('libtensorflow_cc',
          dirs: tensorflow_libdir, required: false)``` fails on macos despite anything I can do to persuade it otherwise/

Firstly I removed the requirement to actually find tf_tensorflow_lib from meson.build:

```
diff --git a/lc0/meson.build b/lc0/meson.build
index ce81266..7976991 100644
--- a/lc0/meson.build
+++ b/lc0/meson.build
@@ -96,7 +96,7 @@ tf_tensorflow_lib = cc.find_library('libtensorflow_cc',
 tf_protobuf_lib = cc.find_library('libprotobuf',
           dirs: tensorflow_libdir, required: false)
 
-if tf_dl_lib.found() and tf_tensorflow_lib.found() and tf_protobuf_lib.found()
+if tf_dl_lib.found() and tf_protobuf_lib.found()
   includes += include_directories(
     tensorflow_include,
     tensorflow_include[0] + '/bazel-genfiles',
```

Running build.sh now produces object file but obviously fails on the linkage stage.

I therefore manually linked from build/release with the following command (which is just the meson generated linkage with -ltensorflow_cc added on to the end):

```
c++  -o lc0 'lc0@exe/src_main.cc.o' 'lc0@exe/src_engine.cc.o' 'lc0@exe/src_analyzer_analyzer.cc.o' 'lc0@exe/src_analyzer_table.cc.o' 'lc0@exe/src_chess_bitboard.cc.o' 'lc0@exe/src_chess_board.cc.o' 'lc0@exe/src_chess_position.cc.o' 'lc0@exe/src_chess_uciloop.cc.o' 'lc0@exe/src_mcts_node.cc.o' 'lc0@exe/src_mcts_search.cc.o' 'lc0@exe/src_neural_cache.cc.o' 'lc0@exe/src_neural_encoder.cc.o' 'lc0@exe/src_neural_factory.cc.o' 'lc0@exe/src_neural_loader.cc.o' 'lc0@exe/src_neural_network_mux.cc.o' 'lc0@exe/src_neural_network_random.cc.o' 'lc0@exe/src_neural_writer.cc.o' 'lc0@exe/src_selfplay_game.cc.o' 'lc0@exe/src_selfplay_loop.cc.o' 'lc0@exe/src_selfplay_tournament.cc.o' 'lc0@exe/src_utils_commandline.cc.o' 'lc0@exe/src_utils_optionsdict.cc.o' 'lc0@exe/src_utils_optionsparser.cc.o' 'lc0@exe/src_utils_random.cc.o' 'lc0@exe/src_utils_string.cc.o' 'lc0@exe/src_utils_transpose.cc.o' 'lc0@exe/src_utils_filesystem.posix.cc.o' 'lc0@exe/src_neural_network_tf.cc.o' -Wl,-dead_strip_dylibs -lpthread -ldl /usr/local/lib/tensorflow_cc/libprotobuf.a -ltensorflow_cc  
```

I don't know enough meson to fully edit the meson.build file to make this happen automatically on macos.

If anyone can get ```cc.find_library('libtensorflow_cc')``` to succeed then that would be the preferred option!

**Comment by gsobala** [comment]
Update: lc0 works with default tensorflow_cc build but segfaults with -march=native tensorflow_cc build.

**Comment by so-much-meta** [comment]
@gsobala - ha, yeah I realized that a few minutes after I posted yesterday. At first, I only checked that it started, assuming that if it loaded weights and a node was selected it was working. Once I saw that it was going way way too fast, and figured out it was random moves, I started trying to get the build working (unsuccessfully) but forgot to post back here... Gonna try again.

**Comment by gsobala** [comment]
Update: Successfully compiled libtensorflow_cc.so with support for FMA and AVX2 with the following changes to tensorflow_cc/tensorflow_cc/cmake/build_tensorflow.sh. (--copt=march=native caused a segfault when running lc0).

Replace line 89
```
bazel build --config=opt \
```
with 
```
bazel build --config=opt --copt=-mavx2 --copt=-mfma \
```

**Comment by so-much-meta** [comment]
@gsobala - awesome... My last tensorflow_cc build ended up looking like this...
```
Replacing links with the copies of their targets.
This may take a while...
cp: ./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/protobuf/include/google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h: File name too long
```

And then a string of dozens of more similar errors (repeated protobuf)... Does this look at all familiar to you?

**Comment by mooskagh** [comment]
I remember someone already having that, in linux..
That protobuf is a symlink, possibly removing it helps.
