### ISSUE TITLE
Windows 10 identifies client.exe as a trojan virus

### ISSUE THREAD

**Issue by science** [glinscott/leela-chess#622]
Windows 10 Defender this morning identified client.exe from Leela Chess Zero (Win GPU) as a virus.
I downloaded the zip file again, to be sure that it's not coming from my machine, and Windows Defender identifies the entire zip file as a trojan virus.

I'd guess Windows Defender has a heuristic to detect clients that consume execution instructions remotely and your exe is behaving in this way? I would think you can contact Microsoft to get this resolved - I'd be happy to help out if I can, but I think I would need email contact info to the core developers to share with MS, before MS anti-virus team would give me the time of day.

Here's a screenshot of the message:
![image](https://user-images.githubusercontent.com/67948/40242113-91294dce-5a71-11e8-99c1-669b0c0373ba.png)

**Comment by science** [comment]
Here's a screenshot of the warning message for the Win GPU zip file:

![image](https://user-images.githubusercontent.com/67948/40242346-4d7db3de-5a72-11e8-872a-e03228ea1df2.png)

**Comment by Graham853** [comment]
I use Windows 10 Defender and get no warnings. That's Windows 10 Home with Creators update.

**Comment by ganeshkrishnan1** [comment]
What is the SHA of the zip file you downloaded?

**Comment by Graham853** [comment]
~~~~
//
// File Checksum Integrity Verifier version 2.05.
//
                MD5                             SHA-1
-------------------------------------------------------------------------
a28e9959b3b8402cc6dc36ccf98e5898 699bcee8475d479392bbc1f59accef0fc106bc14 c:\users\grj\desktop\gpu-win.zip
~~~~

**Comment by science** [comment]
I downloaded the latest RC1 win-gpu install and I am no longer getting warnings. So I'm going to close this ticket - please re-open if that seems like a mistake. Thanks!
