### ISSUE TITLE
lc0 outputs incorrectly a null move or a1a1 when the position is a threefold repetition

### ISSUE THREAD

**Issue by frpays** [glinscott/leela-chess#627]
This is not up to the UCI engine to decide when the game is drawn.

In this game, the UCI engine outputs "a1a1"

position startpos moves g1f3 g8f6 f3g1 f6g8 g1f3 g8f6 f3g1 f6g8
Found network file: /workspace/leela-chess/leela-chess/lc0/build/weights_227.txt
Creating backend [multiplexing]...
Creating backend [cudnn]...
Creating backend [cudnn]...
go movetime 1000
bestmove a1a1

In this game, as (white) lc0 outputs 0000 for it 35th move as white.

  White     leela     
  Black     stockfish
  Result    *         
1    e4      e6      
2    d4      d5      
3    e5      c5      
4    c3      Nc6     
5    Nf3     Bd7     
6    a3      Nge7    
7    b4      c4      
8    a4      f6      
9    g3      a6      
10   exf6    gxf6    
11   Bg2     e5      
12   Nh4     Be6     
13   O-O     Qd7     
14   dxe5    fxe5    
15   f4      O-O-O   
16   b5      Na5     
17   fxe5    Ng6     
18   Bg5     Bc5+    
19   Kh1     Nxe5    
20   Bxd8    Rxd8    
21   Nd2     Ng4     
22   bxa6    bxa6    
23   Qe2     Re8     
24   Rae1    Nc6     
25   Nf5     Nce5    
26   Nd4     Nd3     
27   Rb1     Bf5     
28   Qf3     Ndf2+   
29   Kg1     Bxb1    
30   Rxb1    Rf8     
31   Qe2     Re8     
32   Qf3     Rf8     
33   Qe2     Re8     
34   Qf3     Rf8     
35   Result: *

**Comment by mooskagh** [comment]
It detects it as a terminal node and doesn't try to expand, so it even doesn't know what possible moves are. I'll see what can be done in this particular case.

**Comment by mooskagh** [comment]
Fixed.
