### ISSUE TITLE
PgnViewer Error

### ISSUE THREAD

**Issue by grondilu** [glinscott/leela-chess#65]
While attempting to view one of the games (http://162.217.248.187/game/2151), I got this popping up:

    PgnViewer: Error parsing Bg8Kxg8, Error: unhandled from chars Bg8K

It seems like a space is missing between Bg8 and Kxg8, most likely due to a wrong method for line concatenation or something.  See PR 66

**Comment by jkiliani** [comment]
Strangely, I can view the one training game by @glinscott, but none of the ones by @kiudee

**Comment by jkiliani** [comment]
OK @glinscott already fixed this in https://github.com/glinscott/leela-chess/commit/5b33b1916cbc09fc449e5cca72636ecd4d1ab4ac . I got the client working for me, and can see the games in the viewer. @kiudee hasn't merged the fix yet.

**Comment by jkiliani** [comment]
@glinscott I have a problem with the viewer again, on the computer only (it works on Android phone). Did something change recently with the way games are handled by the server for viewing?
