### ISSUE TITLE
lc0 continues to play games when there's insufficient mating material

### ISSUE THREAD

**Issue by jnewlin12345** [glinscott/leela-chess#651]
https://lichess.org/mUEupz1Z#141

This is from one of the training runs

**Comment by mooskagh** [comment]
@evalon32 maybe you have time to look into that?

**Comment by mooskagh** [comment]
Hm, Is KN vs KN not enough material?
I think that unlike KNN vs K, checkmate is possible.

**Comment by evalon32** [comment]
Both KN vs KN and KNN vs K are sufficient mating material. Checkmate cannot be forced, but is possible:
https://lichess.org/editor/kn6/2N5/1K6/8/8/8/8/8_b_-_-
https://lichess.org/editor/k7/2N5/1KN5/8/8/8/8/8_b_-_-
