### ISSUE TITLE
lc0: print uci info more often

### ISSUE THREAD

**Issue by mooskagh** [glinscott/leela-chess#668]
Currently `lc0` prints updated `uci info` when bestmove/depth/seldepth is changed.
At higher depth it may take a while until something from that list is changed.
It makes sense to print `uci info` also on timer (every 27 seconds, for example).

**Comment by Videodr0me** [comment]
I fixed this in my experimental version. This outputs info approx everry second.
Just added this:
((uci_info_.nodes / (uci_info_.nps+1) )!= ((total_playouts_ + initial_visits_) / (uci_info_.nps+1)))||
in

```c++
void Search::MaybeOutputInfo() {
  SharedMutex::Lock lock(nodes_mutex_);
  Mutex::Lock counters_lock(counters_mutex_);
  if (!responded_bestmove_ && best_move_node_ &&
       (best_move_node_ != last_outputted_best_move_node_ ||
       uci_info_.depth != root_node_->GetFullDepth() ||
       ((uci_info_.nodes / (uci_info_.nps+1) )!= ((total_playouts_ + initial_visits_) / (uci_info_.nps+1)))||
       uci_info_.seldepth != root_node_->GetMaxDepth())) {
    SendUciInfo();
  }
}

**Comment by mooskagh** [comment]
This issue was moved to LeelaChessZero/lc0#18
