### ISSUE TITLE
Wiki/FAQ Gauntlet information

### ISSUE THREAD

**Issue by JamieO53** [glinscott/leela-chess#679]
This information is not being updated:

>  CCLS Rating for LCZ from these gauntlet results 

Instead, use this sheet: https://docs.google.com/spreadsheets/d/1xUO3-MDP5yMcaPzikJGgZ3K3K2ySZs_-fYA-FK4-Q1I/edit#gid=1245059886 and link it to https://www.twitch.tv/ccls. It is great fun watching the games. The changes are made by Carlos Martín Canavessi.

**Comment by killerducky** [comment]
The wiki is open to edit, please feel free to add this.

**Comment by JamieO53** [comment]
Thanks, I have done so.
