### ISSUE TITLE
PGN Parser

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#7]
This will be necessary to implement @gcp's excellent idea to validate the UCT framework.  The PGN parser will need to then dump out training data to allow us to try supervised learning from current expert AI's (SF in this case).

**Comment by brianprichardson** [comment]
Could start with 

https://github.com/niklasf/python-chess

**Comment by Error323** [comment]
I was working on this using human data and python-chess. Ill add it when ready.

**Comment by student-t** [comment]
PGN parser should take no more than an hour on Python.

**Comment by student-t** [comment]
The code for dumping training data is in Training.cpp. The PGN parser should therefore be in C++.

**Comment by Error323** [comment]
Yeah makes sense, OK.

**Comment by student-t** [comment]
From what I see in the source code, we might need to do this:

1. Add a PGN parser in C++ (not hard)
2. Loop over those games like generate_training_games() in UCI.cpp. The function would be "learn_PGN_games()".
3. We need the game results immediately, so the game score integer is -1,0,1 depend on the game result. This will be an argument to training like what play_one_game() returns to Training::dump_training in the current code.
4. We will also need to feed the game moves into Training::record(). One issue I see is that we don't have number of nodes visited (sum_visits).
5. Call "void Training::dump_training(int game_score, OutputChunker& outchunk)" to do the supervised learning.

**Comment by Error323** [comment]
I think we should build a separate binary that converts any file of PGN games to a training set. The move probability vector becomes a one-hot encoding of the move chosen - the PV move in the case of engines playing eachother.

**Comment by glinscott** [comment]
Initial version of PGN parsing and output is done here: https://github.com/glinscott/leela-chess/blob/master/src/main.cpp#L284-L308.  Big thanks to https://github.com/mcostalba/scoutfish, where I got the san_to_move code from.

I'm training on the 80k games that GCP played here: https://sjeng.org/dl/sftrain_clean.pgn.xz

Currently at
```
step 93900, policy loss=3.28019 mse=0.0666218 reg=0.489985 (3636.36 pos/s)
step 94000, policy loss=3.28352 mse=0.0666423 reg=0.490182 (3674.99 pos/s)
step 94000, training accuracy=12.9297%, mse=0.0768878
```
So, the network is learning something at least.  Still not very good though.

**Comment by Error323** [comment]
I'm also training on the 80K games. However I'm completely bounded by CPU from converting the trainingsdata to planes. My two 2Ti cards are mostly idle. What about you @glinscott? What is your batch size? Can we speed up the conversion? I don't see an obvious problem.

**Comment by gcp** [comment]
The training code doesn't have multi-GPU support. 

As for why you can't saturate a single GPU:
a) Chess boards are 6 times faster than Go boards to evaluate, and the default networks is rather small, so it's much easier to be CPU bound.
b) The processing code is very optimized and fully SMP, but you have to be careful to do as little non-numpy and non-TF processing as possible, or it will drop performance. Maybe one of the chess related changes affected that.

You can try increasing the batch size as much as possible, e.g. to 1024, 2048 or 4096.

**Comment by Error323** [comment]
Currently using a batch size of 8192. The chess trainingdata has much more planes to convert from hex. I don't see an obvious speedup/performance gain to be made.

**Comment by glinscott** [comment]
I'm not a tensorflow expert, but perhaps we can store the training data in it's internal format?  That would eliminate all the conversion overhead.

**Comment by Error323** [comment]
Ok I've implemented your suggestion, generated 100K examples in raw tensorflow proto format, speed doubles roughly. Gonna let this continue now.

```
step 100, policy loss=7.51403 mse=0.093901 reg=0.254125 (0 pos/s)
step 200, policy loss=7.42882 mse=0.0927447 reg=0.253955 (6650.52 pos/s)
step 300, policy loss=7.34537 mse=0.091787 reg=0.253639 (6534.35 pos/s)
step 400, policy loss=7.25372 mse=0.0908142 reg=0.25322 (6436.91 pos/s)
step 500, policy loss=7.17023 mse=0.0900301 reg=0.252754 (6348.16 pos/s)
step 600, policy loss=7.08359 mse=0.0891327 reg=0.252332 (6359.86 pos/s)
step 700, policy loss=7.00339 mse=0.0883775 reg=0.251795 (6454.53 pos/s)
step 800, policy loss=6.9277 mse=0.0875354 reg=0.251144 (6491.59 pos/s)
step 900, policy loss=6.85841 mse=0.0868997 reg=0.250389 (6496.51 pos/s)
step 1000, policy loss=6.7935 mse=0.0861936 reg=0.24954 (6474.87 pos/s)
```

**Comment by glinscott** [comment]
@Error323 Awesome!  That's a big speed-up.  How much work was the code?

**Comment by Error323** [comment]
@glinscott Not much, but a bit hacky. I'll create a PR after cleaning up? Were probably gonna do more supervised experimentation.
