### ISSUE TITLE
Create tournament layout

### ISSUE THREAD

**Issue by Ilis** [glinscott/leela-chess#706]
Create tournament layout is a bit broken

![default](https://user-images.githubusercontent.com/1223140/41759292-125684c4-7607-11e8-9367-77268913d203.png)

**Comment by mooskagh** [comment]
The correct repository for lichess is https://github.com/ornicar/lila/issues

This repository is about LeelaChessZero, the open source implementation of Google DeepMind AlphaZero.

**Comment by Ilis** [comment]
Ohhh, sorry!
