### ISSUE TITLE
Project lacks software license

### ISSUE THREAD

**Issue by zediir** [glinscott/leela-chess#78]
There's no COPYING file to tell what OSS license Leela Zero Chess is licensed under. Files copied from leela zero like https://github.com/glinscott/leela-chess/blob/master/src/config.h and from stockfish https://github.com/glinscott/leela-chess/blob/master/src/Bitboard.cpp have license comment but for example https://github.com/glinscott/leela-chess/blob/master/src/pgn.cpp lacks it.

>You should have received a copy of the GNU General Public License
>along with this program.  If not, see <http://www.gnu.org/licenses/>.

**Comment by glinscott** [comment]
Done in 6213d9e9592b549571997deceae9c89044b3ffe2.
