### ISSUE TITLE
Port autogtp to chess/UCI

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#8]
I haven't looked in depth yet, but hopefully this won't be too much effort.

**Comment by gcp** [comment]
Just launching cutechess-cli would be a perfectly acceptable substitute. There was no cutechess-cli for go, or rather, autogtp originally was my implementation of it :-)

**Comment by glinscott** [comment]
Yes, good point!  Autogtp also manages the communication with the server though, so we'd still want that part of it.
