### ISSUE TITLE
-t 1 --seed N not deterministic

### ISSUE THREAD

**Issue by killerducky** [glinscott/leela-chess#84]
The problem is this code: `seed = cfg_rng_seed ^ (std::uint64_t)thread_id`. We need to not mix in the thread_id at least for this case. I'm not sure exactly how this is all supposed to fit together, @Error323 can you look at this?

**Comment by Error323** [comment]
Hmmm I think we should enforce using only 1 thread when a seed is given on the commandline. The deterministic property is lost anyway when using more threads.
