### ISSUE TITLE
Store every ~nth entry in a chunk.

### ISSUE THREAD

**Issue by Error323** [glinscott/leela-chess#85]
From experience with the data, both supervised and unsupervised, it seems that training on every 16th+r with r randomly in {0,1} position instead of full games makes it very robust against overfitting. It will also reduce the bandwidth on the server and helps training speed.

Thoughts?

**Comment by killerducky** [comment]
Especially for the value head we need to skip positions like that. But when we have all the data, we can pick a different 1/16th set of positions for each epoch. The same chunk/game is used for many epochs during it's lifetime in the sliding 500K window, so keeping them all will be beneficial.

Maybe switching the training files to binary would help? I didn't look closely but LZ has something for the backend now: https://github.com/gcp/leela-zero/pull/917

**Comment by Error323** [comment]
Thanks, I fully agree with this and will look into lz's backend.
