### ISSUE TITLE
Insufficient mating material rule is not observed in selfplay

### ISSUE THREAD

**Issue by evalon32** [glinscott/leela-chess#89]
Position::is_draw() doesn't cover draw by insufficient mating material (such as K+N v K or even K v K). Is this intentional? It seems like a lot of the longer games reach such positions and then continue until 3-fold rep or 50-move or 450-ply draw, which is wasteful.

On the one hand, the conditions for "insufficient mating material" (theoretical impossibility of a checkmate) are human knowledge, but on the other hand, they are, in fact, part of the official rules.

**Comment by jkiliani** [comment]
Agreed, seems more efficient to truncate any K v K, K v N and K v B endings.

**Comment by Error323** [comment]
Agreed, @evalon32 you want to make a pull request on it?

**Comment by evalon32** [comment]
@Error323 I'd love to, but can't until #78 is resolved.

**Comment by Error323** [comment]
@evalon32 what would be a good solution for #78? @glinscott could you have a look?

**Comment by jkiliani** [comment]
I also asked @gcp about this, maybe he could help too...

**Comment by jjoshua2** [comment]
I think we should use 3 piece syzygy tb adjudication like cutechess does. Once we are adjudicating draws to speed things up might as well do it well instead of adding special cases again.

**Comment by evalon32** [comment]
@Error323 A good solution would be adding a COPYING file or similar :)

**Comment by jjoshua2** [comment]
I made a pull request for KvK being a draw https://github.com/jjoshua2/leela-chess/pull/1
Its super simple just adding popcount(pos.pieces() == 2

**Comment by jjoshua2** [comment]
Here is a pull for doing 3 piece syzygy adjudication. Also needs the tbprobe.cpp and .h and the 3 piece syzygy files:
https://github.com/jjoshua2/leela-chess/compare/master...jjoshua2-patch-2?quick_pull=1

**Comment by jjoshua2** [comment]
I think we need a little direction from the powers that be on which method they want to pursue?

**Comment by glinscott** [comment]
Adding tbprobe seems like a fairly big step to just adjudicate the endgames.  We can easily detect the material keys for the known draws and adjudicate w/o TBs.  I'm in favor of letting the network learn the KRvK endgames for now.  We can certainly explore adding TB support in later though!

**Comment by jjoshua2** [comment]
How's this look?
`pos.pieces() == 2 || ( pos.pieces() == 3 && pos.pieces(BISHOP) || pos.pieces(KNIGHT) )`
