### ISSUE TITLE
Initial server implementation

### ISSUE THREAD

**Issue by glinscott** [glinscott/leela-chess#9]
Basic python web server probably, I have an Ubuntu 16.04 server set up, just need to deploy it and figure out what we want the API to look like.

**Comment by gcp** [comment]
FYI: https://github.com/gcp/leela-zero-server

Even if you prefer to do your own thing in Python it may give you ideas about the API endpoints (including the hidden ones and match logic).

**Comment by glinscott** [comment]
Thanks @gcp!
