### ISSUE TITLE
Fool's mate :)

### ISSUE THREAD

**Issue by evalon32** [glinscott/leela-chess#90]
If you're easily amused, you might like this game: http://162.217.248.187/game/53341

**Comment by luigio** [comment]
Did Leela play that? :o

**Comment by evalon32** [comment]
Yep. It's a training game my client uploaded to the server.

**Comment by luigio** [comment]
Lesson 1: Don't Fall to the Fool's Mate --> Done!

**Comment by glinscott** [comment]
Fun one :).
